-- ============================================================================
-- GENERATED by scripts/split_schema.py from nce/schema.sql -- DO NOT EDIT BY HAND.
--
-- RUNTIME half of schema.sql
--
-- Runs on EVERY connect, exactly as the whole of schema.sql does today. Re-asserting
-- these is how function and policy updates reach an existing database, and how the
-- tenant-isolation loop self-heals. Anything ambiguous lives here rather than in
-- bootstrap, because staying here preserves current behaviour.
--
-- Regenerate:  python scripts/split_schema.py --out-dir nce/
-- Verify:      python scripts/split_schema.py --check
-- ============================================================================

-- ============================================================================
-- TriMCP — PostgreSQL Schema
-- Loaded by nce.orchestrator.NCEEngine._init_pg_schema on connect().
--
-- All statements are idempotent (IF NOT EXISTS). Safe to run on every startup.
-- Hardening applied: pgcrypto, HNSW cosine indexes, TIMESTAMPTZ, CHECK on
-- confidence, compound index for recall, updated_at on upserted KG tables,
-- CHAR(24) mongo_ref_id (MongoDB ObjectId hex length), NOT NULL where Saga
-- semantics forbid orphans.
-- ============================================================================

-- --- Extensions ---
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- --- Application roles (required before any RLS policy references nce_app) ---
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        CREATE ROLE nce_app WITH LOGIN PASSWORD 'nce_app_secret';
    ELSE
        ALTER ROLE nce_app WITH LOGIN PASSWORD 'nce_app_secret';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_gc') THEN
        CREATE ROLE nce_gc BYPASSRLS NOLOGIN;
    ELSE
        ALTER ROLE nce_gc BYPASSRLS NOLOGIN;
    END IF;
END $$;

-- --- Knowledge-graph nodes (partitioned by HASH) ---
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'kg_nodes' AND c.relkind = 'r' AND c.relispartition = false AND NOT EXISTS (SELECT 1 FROM pg_partitioned_table WHERE partrelid = c.oid)) THEN
        ALTER TABLE kg_nodes RENAME TO kg_nodes_old;
    END IF;
END $$;

-- --- Knowledge-graph edges (partitioned by HASH) ---
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relname = 'kg_edges' AND c.relkind = 'r' AND c.relispartition = false AND NOT EXISTS (SELECT 1 FROM pg_partitioned_table WHERE partrelid = c.oid)) THEN
        ALTER TABLE kg_edges RENAME TO kg_edges_old;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON kg_node_embeddings TO nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON kg_node_embeddings_0 TO nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON kg_node_embeddings_1 TO nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON kg_node_embeddings_2 TO nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON kg_node_embeddings_3 TO nce_app;
        
        GRANT DELETE ON pii_redactions TO nce_app;
        IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pii_redactions_default') THEN
            GRANT DELETE ON pii_redactions_default TO nce_app;
        END IF;
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON snapshots FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON snapshots TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — snapshot GRANTs skipped (create role or run migrations)';
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON replay_runs FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON replay_runs TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — replay_runs GRANTs skipped';
    END IF;
END $$;

-- Fail-fast session namespace for RLS policies (see nce/auth.set_namespace_context).
CREATE OR REPLACE FUNCTION get_nce_namespace() RETURNS uuid AS $$
DECLARE
    val text;
BEGIN
    val := nullif(trim(current_setting('nce.namespace_id', true)), '');
    IF val IS NULL THEN
        RAISE EXCEPTION 'nce.namespace_id is not set for this transaction';
    END IF;
    BEGIN
        RETURN val::uuid;
    EXCEPTION
        WHEN invalid_text_representation THEN
            RAISE EXCEPTION 'nce.namespace_id is not a valid UUID: %', val;
    END;
END;
$$ LANGUAGE plpgsql STABLE;

-- C3 external-principal scope accessor (migration 028).
-- Returns the nil UUID (deny-sentinel) when nce.external_scope_id is unset/empty,
-- guaranteeing zero rows are visible — deny-when-unset invariant.
-- See nce/migrations/028_c3_external_scope_rls.sql for full documentation.
-- INVARIANT: no real external_scope_id column may store the nil UUID.
CREATE OR REPLACE FUNCTION get_nce_external_scope() RETURNS uuid AS $$
DECLARE
    val text;
BEGIN
    val := nullif(trim(current_setting('nce.external_scope_id', true)), '');
    IF val IS NULL THEN
        RETURN '00000000-0000-0000-0000-000000000000'::uuid;
    END IF;
    BEGIN
        RETURN val::uuid;
    EXCEPTION
        WHEN invalid_text_representation THEN
            RETURN '00000000-0000-0000-0000-000000000000'::uuid;
    END;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION get_nce_external_scope() IS
'C3 external-principal RLS accessor. Returns session external_scope_id or nil-UUID
deny-sentinel when unset. Use in external_isolation_policy USING expressions.';

ALTER TABLE replay_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE replay_runs FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS namespace_isolation_policy ON replay_runs;
DROP POLICY IF EXISTS tenant_isolation_policy ON replay_runs;
CREATE POLICY tenant_isolation_policy ON replay_runs
    FOR ALL TO nce_app
    USING (
        source_namespace_id IS NOT NULL
        AND source_namespace_id = get_nce_namespace()
    )
    WITH CHECK (
        source_namespace_id IS NOT NULL
        AND source_namespace_id = get_nce_namespace()
    );

-- Monthly partition windows (UTC); keeps hot data off the DEFAULT catch-all partition
CREATE OR REPLACE FUNCTION nce_ensure_event_log_monthly_partitions(p_months_ahead int DEFAULT 3)
RETURNS void
LANGUAGE plpgsql
AS $fn$
DECLARE
    m int;
    p_start timestamptz;
    p_end timestamptz;
    p_name text;
    violating_count int;
BEGIN
    IF p_months_ahead < 0 THEN
        RAISE EXCEPTION 'p_months_ahead must be >= 0';
    END IF;
    FOR m IN 0..p_months_ahead LOOP
        p_start := date_trunc('month', now() + make_interval(months => m));
        p_end := p_start + interval '1 month';
        p_name := 'event_log_' || to_char(p_start, 'YYYY_MM');
        IF to_regclass(format('public.%I', p_name)) IS NULL THEN
            -- Check if there are violating rows in event_log_default
            EXECUTE format(
                'SELECT count(*)::int FROM event_log_default WHERE occurred_at >= %L AND occurred_at < %L',
                p_start,
                p_end
            ) INTO violating_count;
            
            IF violating_count > 0 THEN
                -- Move violating rows from event_log_default to a temp table
                CREATE TEMP TABLE temp_event_log_migrate ON COMMIT DROP AS 
                    SELECT * FROM event_log_default 
                    WHERE occurred_at >= p_start AND occurred_at < p_end;
                    
                DELETE FROM event_log_default 
                WHERE occurred_at >= p_start AND occurred_at < p_end;
                
                -- Create partition
                EXECUTE format(
                    'CREATE TABLE %I PARTITION OF event_log FOR VALUES FROM (%L) TO (%L)',
                    p_name,
                    p_start,
                    p_end
                );
                
                -- Insert them back into event_log so they route to the new partition
                INSERT INTO event_log SELECT * FROM temp_event_log_migrate;
                
                -- Drop the temp table
                DROP TABLE temp_event_log_migrate;
            ELSE
                EXECUTE format(
                    'CREATE TABLE %I PARTITION OF event_log FOR VALUES FROM (%L) TO (%L)',
                    p_name,
                    p_start,
                    p_end
                );
            END IF;
        END IF;
    END LOOP;
END;
$fn$;

SELECT nce_ensure_event_log_monthly_partitions(3);

DO $$
BEGIN
    REVOKE ALL ON event_log FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT INSERT, SELECT ON event_log TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — event_log GRANTs skipped (create role or run migrations)';
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON event_sequences FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT INSERT, SELECT, UPDATE ON event_sequences TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — event_sequences GRANTs skipped (create role or run migrations)';
    END IF;
END $$;

-- FIX-064 / FIX-065: parent_event_id triggers validate or UPDATE without a partition key,
-- causing partition merge-appends; SET NULL path is also incompatible with WORM.
-- Partition-safe policy is deferred (FIX-067); Merkle chain provides integrity.
DROP TRIGGER IF EXISTS trg_event_log_parent_fk ON event_log;
DROP TRIGGER IF EXISTS trg_event_log_parent_fk_insupd ON event_log;
DROP TRIGGER IF EXISTS trg_event_log_parent_fk_del ON event_log;
DROP TRIGGER IF EXISTS trg_event_log_parent_set_null ON event_log;
DROP FUNCTION IF EXISTS trg_event_log_parent_fk();
DROP FUNCTION IF EXISTS trg_event_log_parent_set_null();

-- WORM immutability: reject any UPDATE or DELETE on event_log.
CREATE OR REPLACE FUNCTION prevent_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'event_log is immutable (WORM). % operation is forbidden.', TG_OP;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Salience decay UDF (Item B): pushes Ebbinghaus decay into PostgreSQL
CREATE OR REPLACE FUNCTION nce_decayed_score(
    s_last FLOAT,
    updated_at TIMESTAMPTZ,
    half_life_days FLOAT
) RETURNS FLOAT AS $$
DECLARE
    delta_t FLOAT;
    decay_constant FLOAT;
    exponent FLOAT;
    MAX_EXP CONSTANT FLOAT := 20.0;
BEGIN
    IF half_life_days <= 0 THEN
        RETURN s_last;
    END IF;
    delta_t := GREATEST(0.0, EXTRACT(EPOCH FROM (NOW() - updated_at)) / 86400.0);
    decay_constant := LN(2) / half_life_days;
    exponent := LEAST(decay_constant * delta_t, MAX_EXP);
    RETURN s_last * EXP(-exponent);
END;
$$ LANGUAGE plpgsql STABLE;

DO $$
BEGIN
    -- Install WORM immutability trigger (legacy parent-FK triggers dropped above).
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_event_log_worm') THEN
        CREATE TRIGGER trg_event_log_worm
            BEFORE UPDATE OR DELETE ON event_log
            FOR EACH ROW EXECUTE FUNCTION prevent_mutation();
    END IF;
    -- RL-H18 / migration 080: a row trigger cannot fire on TRUNCATE, which
    -- deallocates storage without visiting rows. Only a statement-level
    -- trigger can refuse it. prevent_mutation() reports TG_OP, so this
    -- raises 'TRUNCATE operation is forbidden' with no function change.
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_event_log_worm_truncate') THEN
        CREATE TRIGGER trg_event_log_worm_truncate
            BEFORE TRUNCATE ON event_log
            FOR EACH STATEMENT EXECUTE FUNCTION prevent_mutation();
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON a2a_grants FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT INSERT, SELECT, UPDATE ON a2a_grants TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — a2a_grants GRANTs skipped (create role or run migrations)';
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON resource_quotas FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON resource_quotas TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — resource_quotas GRANTs skipped (create role or run migrations)';
    END IF;
END $$;

DO $$
BEGIN
    REVOKE ALL ON dead_letter_queue FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE ON dead_letter_queue TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — dead_letter_queue GRANTs skipped';
    END IF;
END $$;

ALTER TABLE outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE outbox_events FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS namespace_isolation_policy ON outbox_events;
DROP POLICY IF EXISTS tenant_isolation_policy ON outbox_events;
CREATE POLICY tenant_isolation_policy ON outbox_events
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    REVOKE ALL ON outbox_events FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON outbox_events TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — outbox_events GRANTs skipped';
    END IF;
END $$;

ALTER TABLE saga_execution_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE saga_execution_log FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS namespace_isolation_policy ON saga_execution_log;
DROP POLICY IF EXISTS tenant_isolation_policy ON saga_execution_log;
CREATE POLICY tenant_isolation_policy ON saga_execution_log
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    REVOKE ALL ON saga_execution_log FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE ON saga_execution_log TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — saga_execution_log GRANTs skipped';
    END IF;
END $$;

ALTER TABLE entity_merge_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE entity_merge_queue FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON entity_merge_queue;
CREATE POLICY tenant_isolation_policy ON entity_merge_queue
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE entity_merge_queue FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE entity_merge_queue TO nce_app;
    END IF;
END $$;

-- product_catalog is a GLOBAL shared parts library (Sindre's ruling, 2026-09-04)
-- -- see nce/migrations/064_product_catalog_global.sql. This block mirrors that
-- migration's end state for databases created before it, and EVERY statement is
-- idempotent because _init_pg_schema re-executes this file on every connect().
DROP POLICY IF EXISTS tenant_isolation_policy ON product_catalog;
DROP POLICY IF EXISTS namespace_isolation_policy ON product_catalog;
ALTER TABLE product_catalog NO FORCE ROW LEVEL SECURITY;
ALTER TABLE product_catalog DISABLE ROW LEVEL SECURITY;

-- product_catalog left the tenant_tables loop below, which was its only GRANT
-- site, so nce_app's privileges are granted explicitly here.
DO $BODY$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE product_catalog TO nce_app;
    END IF;
END $BODY$;

COMMENT ON TABLE product_catalog IS
'ETIM-coded product catalog: 552k-row streaming-upsert master for multi-source ingestion.
Deduped on (manufacturer, mfr_part_no); GTIN is the universal key (nullable).
etim_specs JSONB holds coded (etim_class, feature, value, unit) tuples with per-field
provenance and confidence inside the JSONB. product_source_id tracks per-source provenance
for multi-source dedup. is_deleted enables soft-delete. FORCE RLS isolates per tenant.';

COMMENT ON TABLE product_prices IS
'Product pricing: 1.57M cost/list/BID rows (mfr_part_no, supplier, bid_id) natural key.
Streaming-upsert target for price syncs. FORCE RLS isolates per tenant.';

ALTER TABLE product_match_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_match_feedback FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON product_match_feedback;
CREATE POLICY tenant_isolation_policy ON product_match_feedback
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE product_match_feedback FROM nce_app;
        GRANT SELECT, INSERT ON TABLE product_match_feedback TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE product_match_feedback IS
'Append-only learning table for BOM-line match decisions.
Records accept/override decisions from the product_match_bom_line tool so
the C1 resolve() primitive can be recalibrated over time.  Never UPDATE or
DELETE rows — event-sourced learning loop.  FORCE RLS isolates per tenant.';

ALTER TABLE product_enrichment_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_enrichment_log FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON product_enrichment_log;
CREATE POLICY tenant_isolation_policy ON product_enrichment_log
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE product_enrichment_log FROM nce_app;
        GRANT SELECT, INSERT ON TABLE product_enrichment_log TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE product_enrichment_log IS
'Append-only review-queue backing store for on-demand product enrichment proposals.
Each row is one field proposal: field_name + field_value + verbalized confidence (A4) +
needs_review flag.  Money/legal fields (§9.3) and sub-threshold proposals are always
written with needs_review=True.  High-confidence non-money/legal fields may additionally
be merged into product_catalog.etim_specs (the JSONB designed for per-field provenance).
Never UPDATE or DELETE rows — WORM review log.  FORCE RLS isolates per tenant.';

ALTER TABLE procurement_bid_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE procurement_bid_prices FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON procurement_bid_prices;
CREATE POLICY tenant_isolation_policy ON procurement_bid_prices
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE procurement_bid_prices FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE procurement_bid_prices TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE procurement_bid_prices IS
'Procurement consumer cache for Product''s BID/supplier-price projections.
Fed via upsert_bid_projection() from Product''s A2A projection push — not a
primary Nettailer ingest (§9.1: Product owns the single feed).  Natural key is
(namespace_id, artnr, leverandor, bid_id); ON CONFLICT DO UPDATE keeps cache
current.  do_resolve_bids() reads this cache for best-BID-per-artnr resolution.
FORCE RLS isolates per tenant.';

ALTER TABLE system_design_device_capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_design_device_capabilities FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON system_design_device_capabilities;
CREATE POLICY tenant_isolation_policy ON system_design_device_capabilities
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE system_design_device_capabilities FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE system_design_device_capabilities TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE system_design_device_capabilities IS
'Phase-2 device capability attributes for the System Design engine.
Keyed by (namespace_id, node_label) — node_label matches kg_nodes.label.
Column schema follows the AVIXA AV Device Revit Parameter List (Phase 2.1).
kg_nodes has no payload column; typed/queryable capability fields live here.
FORCE RLS isolates per tenant (mirrors procurement_bid_prices pattern).';

ALTER TABLE economy_bom_actual_costs ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_bom_actual_costs FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON economy_bom_actual_costs;
CREATE POLICY tenant_isolation_policy ON economy_bom_actual_costs
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE economy_bom_actual_costs FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE economy_bom_actual_costs TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE economy_bom_actual_costs IS
'Economy-owned actual-cost-per-BOM-line table (Module 8, Wave 5, round 2).
do_cascade_on_approval (nce/vertical_modules/economy/cascade.py) is the SOLE
writer -- the clean decomposition of the BOM_LINE "5-writer race" (roadmap
§9.1): content is Sales-frozen, status transitions belong to
Procurement/Warehouse/Field Tech, and actual_cost belongs to the Economy
cascade alone. Natural-keyed (namespace_id, bom_line_label,
source_approval_id) -- ONE ROW PER (line, approval); INSERT ... ON CONFLICT
DO NOTHING, so a replay of the same approval is a no-op by construction and a
DIFFERENT approval against the same line is a new row rather than an
overwrite (round 1''s `DO UPDATE SET actual_cost = EXCLUDED.actual_cost`
silently lost an earlier approval''s cost -- see migration 047''s header
comment). The line''s actual cost is SUM(actual_cost) grouped by
(namespace_id, bom_line_label), computed by the cascade -- never stored as a
single scalar. A negative actual_cost row is a legitimate credit note.
FORCE RLS isolates per tenant (mirrors procurement_bid_prices pattern).';

ALTER TABLE economy_postings ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_postings FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON economy_postings;
CREATE POLICY tenant_isolation_policy ON economy_postings
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE economy_postings FROM nce_app;
        -- Append-only ledger (WORM), round-3 fix: withhold UPDATE/DELETE
        -- from nce_app at the grant level, following this repo's own
        -- precedent -- event_log grants nce_app only INSERT, SELECT
        -- (schema.sql), deliberately withholding UPDATE/DELETE. No shipped
        -- code path issues UPDATE/DELETE against economy_postings (graph.py's
        -- persist_financial_event is the sole writer and is INSERT-only),
        -- but nce_app is the application's general role, so any future bug,
        -- admin raw-SQL tool, or correction script would otherwise hit an
        -- unguarded table. Corrections must instead go through compensating
        -- reversal postings -- standard ledger practice, now enforced
        -- structurally rather than left to convention. Idempotent: REVOKE
        -- ALL first means a re-run always converges on exactly SELECT,
        -- INSERT regardless of what an earlier version of this migration
        -- granted.
        GRANT SELECT, INSERT ON TABLE economy_postings TO nce_app;
    END IF;
END $$;

-- Storage-level sum=0 backstop (migration 048) -- AFTER INSERT STATEMENT-level
-- trigger using a transition table so a multi-row insert for one event is
-- checked once against the full stored set for that (namespace_id, event_id).
-- Tolerance matches the application-level epsilon (0.01 NOK), not bit-exact
-- zero -- see migration 048's header comment.
CREATE OR REPLACE FUNCTION economy_postings_assert_balanced() RETURNS TRIGGER AS $BODY$
DECLARE
    bad RECORD;
BEGIN
    FOR bad IN
        SELECT ep.namespace_id AS ns, ep.event_id AS eid, SUM(ep.amount) AS total
        FROM economy_postings ep
        JOIN (SELECT DISTINCT namespace_id, event_id FROM new_postings) np
          ON np.namespace_id = ep.namespace_id AND np.event_id = ep.event_id
        GROUP BY ep.namespace_id, ep.event_id
        HAVING ABS(SUM(ep.amount)) > 0.01
    LOOP
        RAISE EXCEPTION
            'economy_postings: event % (namespace %) does not balance to zero (sum=%, tolerance=+/-0.01)',
            bad.eid, bad.ns, bad.total;
    END LOOP;
    RETURN NULL;
END;
$BODY$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_economy_postings_assert_balanced ON economy_postings;
CREATE TRIGGER trg_economy_postings_assert_balanced
    AFTER INSERT ON economy_postings
    REFERENCING NEW TABLE AS new_postings
    FOR EACH STATEMENT
    EXECUTE FUNCTION economy_postings_assert_balanced();

COMMENT ON TABLE economy_postings IS
'Economy-owned balanced-ledger table (Module 8, Wave 6). One row per posting
LINE within a balanced financial event (do_emit_financial_event validates the
whole event balances to zero within epsilon BEFORE any write reaches here --
see nce/vertical_modules/economy/events.py). event_id is the event''s own
deterministic content hash, shared with the corresponding POSTING kg_node
label (POSTING:{event_id}). Natural-keyed (namespace_id, event_id, line_no) --
ONE ROW PER (event, line); INSERT ... ON CONFLICT DO NOTHING, so a replay of
the identical event is a no-op by construction, never a silent overwrite
(mirrors economy_bom_actual_costs, migration 047). `amount` is signed --
direction follows the sign, never a separate debit/credit column pair.
trg_economy_postings_assert_balanced is a STORAGE-level backstop (not a
replacement for the application-level guard in events.py): it re-checks
SUM(amount)=0 within +/-0.01 NOK per (namespace_id, event_id) after every
INSERT, using a transition table so a multi-row insert for one event is
checked once against the full stored set for that event. FORCE RLS isolates
per tenant (mirrors procurement_bid_prices / economy_bom_actual_costs).
Round-3 fixes: nce_app is granted only SELECT, INSERT (append-only/WORM,
mirrors event_log) -- corrections must be compensating reversal postings,
never an UPDATE/DELETE; and ck_economy_postings_account_nonempty rejects an
empty or whitespace-only `account` at the DB level, independently of
graph.py''s own guard (the same non-empty-after-TRIM CHECK pattern as
migration 033''s owner_engine constraint).';

DO $$
BEGIN
    REVOKE ALL ON settings FROM PUBLIC;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON settings TO nce_app;
    ELSE
        RAISE NOTICE 'nce_app role not found — settings GRANTs skipped';
    END IF;
END $$;

-- Attach WORM trigger on event_parents (reusing prevent_mutation)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_event_parents_worm') THEN
        CREATE TRIGGER trg_event_parents_worm
            BEFORE UPDATE OR DELETE ON event_parents
            FOR EACH ROW EXECUTE FUNCTION prevent_mutation();
    END IF;
    -- RL-H18 / migration 080: a row trigger cannot fire on TRUNCATE, which
    -- deallocates storage without visiting rows. Only a statement-level
    -- trigger can refuse it. prevent_mutation() reports TG_OP, so this
    -- raises 'TRUNCATE operation is forbidden' with no function change.
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_event_parents_worm_truncate') THEN
        CREATE TRIGGER trg_event_parents_worm_truncate
            BEFORE TRUNCATE ON event_parents
            FOR EACH STATEMENT EXECUTE FUNCTION prevent_mutation();
    END IF;
END $$;
ALTER TABLE topology_graph ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS topology_graph_tenant_isolation ON topology_graph;
CREATE POLICY topology_graph_tenant_isolation ON topology_graph
    FOR ALL
    USING (namespace_id = get_nce_namespace());
GRANT SELECT, INSERT, UPDATE, DELETE ON topology_graph TO nce_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON topology_graph TO nce_gc;

-- FIX-055: kg_node_embeddings are global (not namespace-scoped).
ALTER TABLE kg_node_embeddings DISABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t text;
    tenant_tables text[] := ARRAY[
        'memories',
        'kg_nodes',
        'kg_edges',
        'pii_redactions',
        'memory_salience',
        'contradictions',
        'snapshots',
        'event_log',
        'resource_quotas',
        'consolidation_runs',
        'bridge_subscriptions',
        'dead_letter_queue',
        'embedding_migrations',
        'memory_embeddings',
        'embedding_aspects',
        'active_learning_queue',
        'd365_integrations',
        'd365_netbox_mappings',
        'd365_sync_runs',
        'd365_delta_tokens',
        'node_ownership_registry',
        'entity_merge_queue',
        'source_mode_config',
        'processed_outbox_events',
        'actor_trust',
        'event_parents',
        'action_approval_queue',
        'action_idempotency',
        -- diagnostics tables (migration 025 — Batch 67)
        'diag_ingestions',
        'diag_anomalies',
        'device_health_rollup',
        -- vertical-engine tables (ml/foundation)
        'divergence_log',
        'product_prices',
        'procurement_bid_prices',
        'system_design_device_capabilities',
        'sales_read_model',
        'sales_targets',
        'sales_signed_baselines',
        'vendor_scorecards',
        'agreement_review_queue',
        'agreement_extraction_runs'
    ];
BEGIN
    FOREACH t IN ARRAY tenant_tables
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS namespace_isolation_policy ON public.%I', t);
        EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_policy ON public.%I', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation_policy ON public.%I '
            'FOR ALL TO nce_app '
            'USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace()) '
            'WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())',
            t
        );
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM nce_app', t);
        IF t IN ('event_log', 'event_parents', 'divergence_log', 'sales_signed_baselines') THEN
            EXECUTE format(
                'GRANT SELECT, INSERT ON TABLE public.%I TO nce_app',
                t
            );
        ELSE
            EXECUTE format(
                'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO nce_app',
                t
            );
        END IF;
        -- Pre-BIGSERIAL databases created this table with a UUID key, so the
        -- sequence may not exist; grant only when it does.
        IF t = 'sales_signed_baselines'
           AND EXISTS (SELECT 1 FROM pg_class WHERE relname = 'sales_signed_baselines_id_seq') THEN
            EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.sales_signed_baselines_id_seq TO nce_app';
        END IF;
    END LOOP;
END $$;


ALTER TABLE a2a_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE a2a_grants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS namespace_isolation_policy ON a2a_grants;
DROP POLICY IF EXISTS tenant_isolation_policy ON a2a_grants;
CREATE POLICY tenant_isolation_policy ON a2a_grants
    FOR ALL TO nce_app
    USING (
        owner_namespace_id = get_nce_namespace()
        OR target_namespace_id = get_nce_namespace()
    )
    WITH CHECK (owner_namespace_id = get_nce_namespace());
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE a2a_grants TO nce_app;

ALTER TABLE contractor_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_profiles FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS external_isolation_policy ON contractor_profiles;
CREATE POLICY external_isolation_policy ON contractor_profiles
    FOR ALL TO nce_app
    USING (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND partner_scope_id IS NOT NULL
        AND partner_scope_id = get_nce_external_scope()
    )
    WITH CHECK (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND partner_scope_id IS NOT NULL
        AND partner_scope_id = get_nce_external_scope()
    );
REVOKE ALL ON TABLE contractor_profiles FROM nce_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE contractor_profiles TO nce_app;


-- =============================================================================
-- Security fix — Domain 5 / D1 HIGH (migration 025 — Batch 67 diag-schema)
-- topology_graph FORCE ROW LEVEL SECURITY
-- =============================================================================
-- topology_graph has had ENABLE ROW LEVEL SECURITY since migration 010, but
-- was never FORCEd.  The table-owner / nce_gc role (BYPASSRLS-adjacent) could
-- therefore bypass the topology_graph_tenant_isolation policy when the session
-- GUC nce.namespace_id is unset — exposing every tenant's infrastructure graph.
--
-- This ALTER is idempotent (safe to re-run).  Kept standalone (not folded into
-- the tenant_tables loop) because topology_graph carries policy name
-- topology_graph_tenant_isolation (from migration 010) whereas the loop creates
-- tenant_isolation_policy; folding would silently rename that policy.
ALTER TABLE topology_graph FORCE ROW LEVEL SECURITY;

ALTER TABLE economy_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE economy_contracts FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON economy_contracts;
CREATE POLICY tenant_isolation_policy ON economy_contracts
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE economy_contracts FROM nce_app;
        -- Live mutable record (not a WORM ledger) -- nce_app gets the full
        -- CRUD set, mirroring economy_bom_actual_costs (migration 047), not
        -- economy_postings' append-only grant (migration 048).
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE economy_contracts TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE economy_contracts IS
'Economy-owned recurring-revenue contract store (Module 8, Wave 10). One row
per (namespace, contract) -- a LIVE mutable record (status/next_renewal_date/
annual_amount change over the contract''s life), unlike the append-only
economy_postings / economy_bom_actual_costs ledgers. Natural-keyed
(namespace_id, contract_id); contracts.py''s do_upsert_contract is the SOLE
writer, using ON CONFLICT DO UPDATE. annual_amount is the single source of
truth for the contract''s value (do_recognize_recurring ratably recognises
1/12 of it per period, Wave 9) -- no separate mrr column, to avoid two money
fields drifting apart. cpi_cap is bounded 0-0.05 by CHECK -- a structural
ceiling no row can exceed, backing do_validate_contract''s per-proposal
enforcement. next_renewal_date drives do_scan_renewals''s 90-day scan.
Retires the Wave-9 namespaces.metadata->economy->recurring_contracts shim
(see recurring.py + cron.py). FORCE RLS isolates per tenant (mirrors
economy_postings / economy_bom_actual_costs).';

ALTER TABLE stock_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_locations FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON stock_locations;
CREATE POLICY tenant_isolation_policy ON stock_locations
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE stock_locations FROM nce_app;
        -- Live mutable record (not a WORM ledger) -- nce_app gets the full
        -- CRUD set, mirroring economy_contracts (migration 049).
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stock_locations TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE stock_locations IS
'Inventory-owned internal LOGISTICS location tree (Module 11, Wave 1). NOT a
customer FUNCTIONAL_LOCATION (system_design/D365''s customer-site tree) --
two trees, not one; see the file header. Hierarchical: warehouse -> zone ->
bin (parent_id chains, level increments); a van is a flat top-level location
(parent_id IS NULL, level = 0), just like a warehouse -- both shapes are
enforced by stock_locations_hierarchy_shape, not left to caller discipline.
schema_seed.py''s seed_warehouse_and_vans is the reference writer: one
warehouse + N vans per namespace, idempotent via the partial unique index
uq_stock_locations_top_level_name. FORCE RLS isolates per tenant; the
self-referencing parent_id FK is composite on (parent_id, namespace_id) so a
hierarchy edge can never cross a tenant boundary.';

ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON inventory_items;
CREATE POLICY tenant_isolation_policy ON inventory_items
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE inventory_items FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE inventory_items TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE inventory_items IS
'Per-SKU-per-location stock row (Module 11, Wave 1) -- the hot
read/atomic-decrement path. One row per (namespace, sku, location)
(inventory_items_natural_key). available = qty_on_hand - qty_reserved -
qty_blocked is computed at read time by a later wave''s do_stock_levels, not
stored here. This row is the SOURCE OF TRUTH for stock-truth reads
(Procurement''s "own stock first", forecast, reservation) -- a future
INVENTORY_ITEM graph node is only an eventually-consistent projection of it,
never the other way around. FORCE RLS isolates per tenant; location_id is a
composite FK on (location_id, namespace_id) into stock_locations so a row can
never reference another tenant''s location.';

ALTER TABLE inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transactions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON inventory_transactions;
CREATE POLICY tenant_isolation_policy ON inventory_transactions
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE inventory_transactions FROM nce_app;
        -- Append-only ledger (WORM), mirrors event_log / economy_postings /
        -- audit_log's precedent: withhold UPDATE/DELETE from nce_app at the
        -- grant level so no application code path -- buggy or future -- can
        -- rewrite history. A correction is a NEW row, never an edit.
        GRANT SELECT, INSERT ON TABLE inventory_transactions TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE inventory_transactions IS
'Append-only movement ledger (Module 11, Wave 11 -- transactions-valuation).
One row per qty change at one (sku, location): do_transfer_stock
(nce/vertical_modules/inventory/stock.py) writes a transfer_out row at
from_location and a transfer_in row at to_location in the SAME transaction as
the inventory_items row write it reflects; do_record_consumption writes one
consumption row. unit_cost rides on this row (inventory_items itself has no
cost column) and enters at inbound -- NULL until a real cost source exists
(Batch 132 goods-receipt); do_valuation
(nce/vertical_modules/inventory/transactions.py) computes FIFO/average value
from these rows per nce/config_data/inventory-valuation.json, and is the
number Inventory hands to Economy to post -- this table and its reader never
post to the GL themselves. FORCE RLS isolates per tenant; nce_app is granted
only SELECT, INSERT -- corrections are new rows, never an UPDATE/DELETE.';

ALTER TABLE inventory_rma ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_rma FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON inventory_rma;
CREATE POLICY tenant_isolation_policy ON inventory_rma
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE inventory_rma FROM nce_app;
        -- UPDATE is granted because Batch 138b transitions the two state
        -- columns (weee_state, stock_movement_state) on this same row. No
        -- DELETE: an RMA row is compliance evidence and nothing in the
        -- application may erase a WEEE disposal record -- a correction is a
        -- new row, never an erased one.
        GRANT SELECT, INSERT, UPDATE ON TABLE inventory_rma TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE inventory_rma IS
'Returns/RMA + WEEE disposal state (Module 11, Wave 10 -- rma-table).
One row per return: do_record_rma (nce/vertical_modules/inventory/rma.py)
INSERT-only creates this row with stock_movement_state = ''pending'' and
records the WEEE compliance lifecycle for the returned item. This table
records; it does not move stock -- no inventory_transactions row is written
on this path and inventory_items is left untouched. Batch 138b performs both
stock legs (restock-on-return and permanent WEEE disposal), transitioning
weee_state / stock_movement_state on this same row via the UPDATE grant
below; Batch 138c (dead-stock-reconcile) reads this table''s settled rows
against the ledger. FORCE RLS isolates per tenant; nce_app is granted
SELECT, INSERT, UPDATE but never DELETE -- an RMA is compliance evidence and
nothing in the application may erase a WEEE disposal record.';

ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON assets;
CREATE POLICY tenant_isolation_policy ON assets
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE assets FROM nce_app;
        -- UPDATE is granted for do_advance_lifecycle, which transitions
        -- lifecycle_state on this same row (09-assets-engine.md, build phase
        -- B1) -- the same forward-provisioning migration 053 did for Batch
        -- 138b. No DELETE: retirement is a lifecycle STATE (RETIRED), never a
        -- deleted row -- an asset register that can forget a device is not a
        -- register. A namespace teardown still removes rows via the
        -- namespace_id FK's ON DELETE CASCADE, which RLS grants do not gate.
        GRANT SELECT, INSERT, UPDATE ON TABLE assets TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE assets IS
'Relational asset register (Module 9, Wave 2 -- seed-from-bom). One row per
originating BOM line: do_seed_asset_from_bom
(nce/vertical_modules/assets/seed.py) is the SOLE writer and is INSERT-only,
creating the row with lifecycle_state taken from
nce/config_data/asset-lifecycle.json''s entry state via Batch 141''s pure
lifecycle module. Idempotency is by DB constraint
(assets_ns_bom_line_uq + INSERT ... ON CONFLICT DO NOTHING), never a
check-then-write. This table is the RELATIONAL half only: the ASSET kg_node
and the BOM_LINE -[installed_as]-> ASSET / ASSET -[lives_in]->
FUNCTIONAL_LOCATION edges are Batch 142b''s, as is ASSET''s row in
node-ownership.json -- no code in this wave writes kg_nodes or kg_edges.
bom_line_id and functional_location_id are identifier columns with NO foreign
key: neither target has a relational home yet (BOM_LINE nodes are Batch
132a, unbuilt; FUNCTIONAL_LOCATION is the unresolved intent->as-built spine
gap, roadmap §9.1). lifecycle_state carries no enumerated CHECK because the
state vocabulary is config-as-IP in asset-lifecycle.json, tuned per tenant.
FORCE RLS isolates per tenant; nce_app is granted SELECT, INSERT, UPDATE
(the UPDATE is for a later wave''s do_advance_lifecycle) but never DELETE --
retirement is the RETIRED lifecycle state, not an erased row.';

COMMENT ON COLUMN goods_receipts.po_ref IS
'Purchase-order reference, stored in ONE normal form: stripped and
UPPER-CASED (goods_receipt.py''s _as_po_ref), the same value hashed into
receipt_hash. Normalising for the hash but storing verbatim -- an earlier
revision of this wave -- made idempotency case-insensitive while this column
and idx_goods_receipts_namespace_po stayed case-sensitive, so a replay was
correctly detected yet a lookup by the canonical case found nothing. Batch
133''s matcher queries this column: match against the upper-cased form.';

COMMENT ON COLUMN goods_receipts.delivery_note_ref IS
'OPTIONAL delivery-note / packing-slip number from the paperwork that arrived
with the goods; stripped and UPPER-CASED like po_ref, blank collapsed to
NULL. PARTICIPATES IN receipt_hash so two genuine PARTIAL deliveries against
the same PO line -- identical location, identical aggregated lines, no scans
-- are two receipts instead of one swallowed replay, while a true retry of
the SAME note remains idempotent. NULL (no note supplied) reproduces the
pre-existing behaviour exactly, collision included.';

COMMENT ON COLUMN goods_receipts.match_result IS
'Reserved for Batch 133''s Receive->Match->Cascade verdict. NULL until that
wave lands; this wave (Batch 132) creates the column and never writes to it.';

ALTER TABLE goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipts FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON goods_receipts;
CREATE POLICY tenant_isolation_policy ON goods_receipts
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE goods_receipts FROM nce_app;
        -- Live mutable-shape record (not a WORM ledger like inventory_transactions)
        -- -- nce_app gets the full CRUD set, mirroring stock_locations/inventory_items
        -- (migration 050). match_result is the one column a LATER wave (Batch 133)
        -- will UPDATE; this wave never does.
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE goods_receipts TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE goods_receipts IS
'Record of one inbound delivery (Module 11, Wave 4 -- goods-receipt, Batch
132). Idempotent on (namespace_id, receipt_hash) -- goods_receipts_idempotency_uq
refuses a duplicate INSERT at the DB level, so a replay (including two
concurrent identical submissions) increments stock exactly once.
receipt_hash covers po_ref, delivery_note_ref, location_id, lines and scans;
supplying delivery_note_ref is how two GENUINE partial deliveries against one
PO line stay two receipts. This row is
the RECORD of the delivery; inventory_items (migration 050) remains the
AUTHORITATIVE stock row and inventory_transactions (migration 051) the
movement ledger -- do_record_goods_receipt increments the former and appends
one goods_receipt-category row per line to the latter, inside the SAME
transaction as this row''s own INSERT. match_result is reserved for Batch
133''s Receive->Match->Cascade verdict and is NULL until then. The graph
projection (GOODS_RECEIPT kg_node, -[against]->PO / -[of]->SKU edges) is
Batch 132b''s -- no kg_node or kg_edge is written from this table or its
writer. FORCE RLS isolates per tenant; location_id is a composite FK on
(location_id, namespace_id) into stock_locations so a receipt can never
reference another tenant''s location.';

-- Index: the primary read path -- geometry for a batch of node labels within
-- one namespace, and the single-row version lookup, are the same shape.
-- (namespace_id, node_label) is already unique-indexed by the UNIQUE above;
-- no second index is added for it.

-- Row-Level Security.
ALTER TABLE system_design_geometry ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_design_geometry FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON system_design_geometry;
CREATE POLICY tenant_isolation_policy ON system_design_geometry
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

-- Application role grants.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE system_design_geometry FROM nce_app;
        -- UPDATE is required: geometry is re-authored in place on every canvas
        -- save, and the version row is incremented rather than appended.
        -- DELETE is granted for parity with the sibling capability table
        -- (migration 039); no code in this wave issues one.
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE system_design_geometry TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE system_design_geometry IS
'Canvas geometry AND the per-DESIGN optimistic-concurrency token for the System
Design engine (Module 6, Wave 14).

TWO KEY GRAINS IN ONE TABLE -- deliberate, and the only exception in this
engine. Most rows are GEOMETRY rows keyed by a NODE label (DEVICE:/PORT:/RACK:/
CABLE:/FL:) carrying x/y, rack_position/rack_face, cable_length_m/cable_type
and meta, with version NULL. Exactly one row per design is the DESIGN VERSION
row, keyed by the DESIGN label (DESIGN:<ID>), carrying version and no geometry.
Distinguish them by version IS NOT NULL (equivalently node_label LIKE
''DESIGN:%''); a geometry row is any row with version NULL. They share a table
because they share the natural key, the tenancy boundary, the lifecycle and the
writer transaction, and because a DESIGN node is never placed on the canvas so
the two grains cannot collide on (namespace_id, node_label).

UNITS AND AXES ARE NORMATIVE (Rev 2 section 4): x/y are CANVAS GRID UNITS with
the origin TOP-LEFT and y increasing DOWNWARD. NCE converts nothing; exporters
convert. Room dimensions are NOT x/y -- they live in meta under
copper.room.w / copper.room.d / copper.room.h, in METERS.

NAMING IS CONTRACTUAL: rack_position and rack_face carry the NetBox vocabulary
(position/face) that Copper follows as a binding ADR. Renaming either breaks
Copper.

version is monotonic per design, starts at 0 and is incremented inside the
authoring write''s own transaction. A caller that supplies expected_version
gets a compare-and-swap; a caller that omits it gets last-writer-wins and the
increment still happens.

SCOPE OF THAT PROMISE: it covers writes made through the two authoring
adapters in nce/vertical_modules/system_design/mcp_handlers.py -- the
system_design_author_topology and system_design_author_functional_location
tools and their REST twins -- and ONLY those. Three other modules under
system_design/ write kg_nodes/kg_edges for a design without passing through
them and never move the token: from_quote.py, to_quote.py and
netbox_bridge.py. All three are unwired today (no non-test callers), so this
is latent rather than exploitable -- but it is not hypothetical, because
read.py''s edge projection filters on subject_label only, so to_quote.py''s
DESIGN -[becomes]-> QUOTE edge would appear in a topology read while version
stood still. Do not read this token as covering every change to a design.

FORCE RLS isolates per tenant, but the pools that serve requests are owner
pools and bypass it -- the real boundary is the explicit namespace_id predicate
in nce/vertical_modules/system_design/geometry.py.';

COMMENT ON COLUMN system_design_geometry.node_label IS
'GRAIN KEY. A node label (DEVICE:/PORT:/RACK:/CABLE:/FL:) on a geometry row;
the DESIGN label on the one version row. Matches kg_nodes.label for geometry
rows.';

COMMENT ON COLUMN system_design_geometry.x IS
'Canvas X in GRID UNITS. Origin TOP-LEFT (Rev 2 section 4). Not meters.';

COMMENT ON COLUMN system_design_geometry.y IS
'Canvas Y in GRID UNITS, increasing DOWNWARD (y-down), origin TOP-LEFT
(Rev 2 section 4). Not meters.';

COMMENT ON COLUMN system_design_geometry.rack_position IS
'NetBox "position": the lowest rack unit this device occupies. NUMERIC(4,1)
carries one decimal place; the HALF-U STEP (a multiple of 0.5) is enforced by
validate_geometry() at the write boundary, NOT by this column -- a direct
INSERT of 1.27 is still rounded to 1.3 silently. Legal range is 0.0 to 999.5
in 0.5 steps; 999.9 fits the column but is not a half-U and is refused.
CONTRACTUAL NAME -- renaming breaks Copper.';

COMMENT ON COLUMN system_design_geometry.rack_face IS
'NetBox "face": ''front'' or ''rear''. CONTRACTUAL NAME AND VOCABULARY --
renaming or extending breaks Copper.';

COMMENT ON COLUMN system_design_geometry.cable_length_m IS
'Cable run length in METERS.';

COMMENT ON COLUMN system_design_geometry.meta IS
'Verbatim passthrough store. Room dimensions live here under copper.room.w /
copper.room.d / copper.room.h, in METERS. NCE stores, Copper interprets
(Rev 2 section 5).';

COMMENT ON COLUMN system_design_geometry.version IS
'Per-DESIGN optimistic-concurrency token. NULL on every geometry row; set only
on the design version row, where it starts at 0 and is incremented by every
authoring write inside that write''s own transaction. Its presence is the
discriminator between the two key grains.';

-- ----------------------------------------------------------------------------
-- Freeze semantics: a BEFORE UPDATE trigger, not a GRANT and not the registry.
-- status / status_changed_at are deliberately OUTSIDE the protected set --
-- content freezes, status keeps advancing. frozen_at itself is immutable
-- once set, independent of the content freeze check.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION reject_frozen_bom_line_mutation() RETURNS TRIGGER AS $BODY$
BEGIN
    IF OLD.frozen_at IS NOT NULL AND NEW.frozen_at IS DISTINCT FROM OLD.frozen_at THEN
        RAISE EXCEPTION
            'bom_line_content.frozen_at is immutable once set (label=%)', OLD.bom_line_label;
    END IF;

    IF OLD.frozen_at IS NOT NULL THEN
        IF NEW.quote_id       IS DISTINCT FROM OLD.quote_id
        OR NEW.line_ref       IS DISTINCT FROM OLD.line_ref
        OR NEW.qty            IS DISTINCT FROM OLD.qty
        OR NEW.unit_price     IS DISTINCT FROM OLD.unit_price
        OR NEW.line_total     IS DISTINCT FROM OLD.line_total
        OR NEW.currency       IS DISTINCT FROM OLD.currency
        OR NEW.origin_kind    IS DISTINCT FROM OLD.origin_kind
        OR NEW.origin_ref     IS DISTINCT FROM OLD.origin_ref
        OR NEW.writer_engine  IS DISTINCT FROM OLD.writer_engine
        THEN
            RAISE EXCEPTION
                'bom_line_content: content is frozen and cannot be mutated (label=%)',
                OLD.bom_line_label;
        END IF;
    END IF;

    RETURN NEW;
END;
$BODY$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_reject_frozen_bom_line_mutation ON bom_line_content;
CREATE TRIGGER trg_reject_frozen_bom_line_mutation
    BEFORE UPDATE ON bom_line_content
    FOR EACH ROW EXECUTE FUNCTION reject_frozen_bom_line_mutation();

ALTER TABLE bom_line_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom_line_content FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON bom_line_content;
CREATE POLICY tenant_isolation_policy ON bom_line_content
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE bom_line_content FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE bom_line_content TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE bom_line_content IS
'Shared, top-level BOM_LINE content store (Module 0, Wave 31 / Batch 132a).
Written by system_design (content:create:design, content:update:design) and
by sales (content:create:manual/package/external,
content:update:manual/package/external, content:freeze) -- guarded per-flow
by node_ownership_registry via nce/bom_lines.py, never engine-prefixed
because both engines write it. Natural-keyed (namespace_id, bom_line_label);
INSERT ... ON CONFLICT DO NOTHING makes a replay of the same
(namespace, label) a no-op by construction. Content (qty/unit_price/
line_total/currency/origin_*) freezes via trg_reject_frozen_bom_line_mutation
once frozen_at is set (from do_freeze_baseline, sales/baseline.py); status
stays mutable after freeze -- see the header comment for the full field-
ownership split. actual_cost is NOT this table''s column -- see
economy_bom_actual_costs (migration 047). FORCE RLS isolates per tenant;
every query must ALSO carry an explicit namespace_id predicate because the
owner/superuser pool used by background jobs bypasses FORCE RLS (bitten three
prior waves: B67, B120, B130).';

-- Index: the primary read path -- state for a batch of node labels within one
-- namespace. (namespace_id, node_label) is already unique-indexed by the
-- UNIQUE above; no second index is added for it, and none is added for a
-- status filter: that filter (B067g2) narrows an already-narrow label set.

-- Row-Level Security.
ALTER TABLE system_design_node_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_design_node_state FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON system_design_node_state;
CREATE POLICY tenant_isolation_policy ON system_design_node_state
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

-- Application role grants.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE system_design_node_state FROM nce_app;
        -- UPDATE is required: a node's status is re-authored in place.
        -- DELETE is granted because W17 MUST delete a node's state row in the
        -- same transaction as the node itself -- see the orphan obligation in
        -- the file header. No code in THIS wave issues one.
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE system_design_node_state TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE system_design_node_state IS
'Per-node lifecycle state for the System Design engine (Module 6, Wave 16):
status, revision and salience for a DEVICE, a RACK or a CABLE.

A SIBLING of system_design_geometry, not a column on it: geometry already
carries two key grains, it does not carry node_type (which the per-type status
CHECK needs on the row), and the wave that reads state never reads geometry.
The accepted cost is that do_get_topology joins two side tables instead of one.

THREE DISTINGUISHABLE STATES, and W17''s retirement guard needs all three:
NO ROW = nothing was ever declared about this node (every pre-W16 node, and it
stays that way until somebody declares something); status IS NULL = we hold
data for this node but nobody declared a lifecycle; status = a value = a
lifecycle was declared. W17 denies on the first two. The writer creates a row
only when the node is genuinely NEW to the authoring call or the caller
supplied an explicit lifecycle key, so an ordinary re-author, a geometry-only
canvas save and a re-author-shaped data-fix all leave a pre-existing node with
no row. NOTHING backfills this table.

status is NULLABLE AND HAS NO COLUMN DEFAULT on purpose: a DEFAULT ''planned''
would be a second, independent source of the one dangerous value, mintable by
any future writer or manual data-fix that never touches the write path.

THE STATUS CHECK IS COMPOSITE, PER node_type. A union CHECK would accept a
CABLE whose status is ''inventory''. The vocabulary is NetBox''s and Copper
follows it as a binding ADR:
  DEVICE -> planned | staged | active | offline | decommissioning | inventory |
            failed
  CABLE  -> planned | connected | decommissioning
  RACK   -> reserved | available | planned | active | deprecated
The CASE''s ELSE branch is FALSE, so an unknown node_type is refused. PORT is
deliberately among the refused: NetBox has no lifecycle status for a port and
none is invented here.

salience is FINITE and NON-NEGATIVE. PostgreSQL numeric NaN is not IEEE NaN --
it compares GREATER than every finite value and equal to itself -- so a stored
NaN would sort as the largest salience in the tenant and silently flip any W17
threshold predicate. Negative is refused because this engine''s own salience
decay clamps at a floor of zero, so a negative has no meaning in NCE.

W17 OBLIGATION: no FK ties a state row to its node (kg_nodes is HASH-partitioned
on label). W17 must delete a node''s state row in the same transaction as the
node, or a later re-author of the same deterministic label inherits the
orphan''s status through ON CONFLICT DO UPDATE.

revision is INERT STORAGE this wave (Copper-side sibling-retirement flow, Rev 2
section 7); it is explicitly NOT the PolyForm-licensed netbox-branching design.

FORCE RLS isolates per tenant, but the pools that serve requests are owner
pools and bypass it -- the real boundary is the explicit namespace_id predicate
in nce/vertical_modules/system_design/devices.py.';

COMMENT ON COLUMN system_design_node_state.node_label IS
'Graph key. Matches kg_nodes.label. One row per node, at most. No FK -- see the
W17 orphan obligation on the table comment.';

COMMENT ON COLUMN system_design_node_state.node_type IS
'The node''s entity_type, on the row because the status vocabulary is per node
type. DEVICE | RACK | CABLE -- the composite CHECK refuses anything else,
including PORT.';

COMMENT ON COLUMN system_design_node_state.status IS
'NetBox lifecycle status, validated per node_type by the composite CHECK.
CONTRACTUAL VOCABULARY -- adding or renaming a value is a Copper contract
change. NULLABLE AND WITHOUT A DEFAULT: NULL means "we hold data for this node,
nobody has declared its lifecycle", which W17 denies on exactly as it denies on
a missing row. A column DEFAULT would be a second source of ''planned'' that no
review of the write path could catch.';

COMMENT ON COLUMN system_design_node_state.revision IS
'Inert storage. Free text, stored verbatim, interpreted by Copper (Rev 2
section 7). NOT the PolyForm-licensed netbox-branching model.';

COMMENT ON COLUMN system_design_node_state.salience IS
'Per-node salience. Stored here because kg_nodes has no salience column.
FINITE and NON-NEGATIVE: PostgreSQL numeric NaN sorts ABOVE every finite value,
so a stored NaN would silently win every W17 threshold comparison.';

-- No further index in this wave, deliberately. The one read this wave
-- performs -- "samples for this asset in this namespace" -- is already served
-- by the leading columns of the unique index behind
-- telemetry_samples_idempotency_uq. The "latest reading per metric" scan that
-- 09-assets-engine.md's do_compute_health will want is a
-- (namespace_id, asset_id, sampled_at DESC) index, and the wave that performs
-- that read owns it -- the same rule migration 054 applied to serial /
-- lifecycle_state.

ALTER TABLE telemetry_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry_samples FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON telemetry_samples;
CREATE POLICY tenant_isolation_policy ON telemetry_samples
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE telemetry_samples FROM nce_app;
        -- SELECT + INSERT only. No UPDATE: a reading that was taken is not
        -- revisable. No DELETE: nothing in the application may erase an
        -- observation, and retention is a later wave's explicit decision (see
        -- the file header). A namespace teardown still removes rows via the
        -- namespace_id FK's ON DELETE CASCADE, which RLS grants do not gate.
        GRANT SELECT, INSERT ON TABLE telemetry_samples TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE telemetry_samples IS
'Manufacturer-telemetry reading stream (Module 9, Wave 5 -- telemetry-adapter).
One row per (namespace, asset, metric, vendor sample instant):
do_pull_telemetry (nce/vertical_modules/assets/telemetry.py) is the SOLE
writer and is INSERT-only. Samples reach it through the TelemetryAdapter
interface; `mock` is the only adapter with real behaviour in this wave and the
five vendor platforms (crestron/qsys/neat/huddly/poly) are env-swap stubs
selected by NCE_ASSETS_TELEMETRY_<PLATFORM>_REAL that raise NotImplementedError
-- no vendor HTTP client, credential or dependency exists yet. Idempotency is
by DB constraint (telemetry_samples_idempotency_uq + INSERT ... ON CONFLICT DO
NOTHING), never a check-then-write, because a telemetry cron re-reads
overlapping windows by design; sampled_at is the VENDOR instant and created_at
the pull instant, and only the former is in the key. NO graph is written from
this table or its writer: the TELEMETRY kg_node and the
ASSET -[monitored_by]-> TELEMETRY edge are a later projection wave''s, and
TELEMETRY has no row in node-ownership.json. asset_id has a SINGLE-column FK
to assets(id) -- it proves the asset exists, NOT that it belongs to this
row''s namespace; that binding comes from FORCE RLS plus do_pull_telemetry''s
namespace-scoped pre-check, and closing the residual needs a
UNIQUE (id, namespace_id) on `assets` that migration 054 does not provide.
FORCE RLS isolates per tenant; nce_app is granted SELECT and INSERT only --
never UPDATE (a reading is not revisable) and never DELETE (retention is a
later wave''s decision).';

ALTER TABLE service_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_tickets FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON service_tickets;
CREATE POLICY tenant_isolation_policy ON service_tickets
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE service_tickets FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE service_tickets TO nce_app;
    END IF;
END $$;

ALTER TABLE sla_clocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE sla_clocks FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON sla_clocks;
CREATE POLICY tenant_isolation_policy ON sla_clocks
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE sla_clocks FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sla_clocks TO nce_app;
    END IF;
END $$;

ALTER TABLE customer_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_health FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON customer_health;
CREATE POLICY tenant_isolation_policy ON customer_health
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE customer_health FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE customer_health TO nce_app;
    END IF;
END $$;

ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON work_orders;
CREATE POLICY tenant_isolation_policy ON work_orders
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE work_orders FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE work_orders TO nce_app;
    END IF;
END $$;

ALTER TABLE checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklists FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON checklists;
CREATE POLICY tenant_isolation_policy ON checklists
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE checklists FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE checklists TO nce_app;
    END IF;
END $$;

ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_entries FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON time_entries;
CREATE POLICY tenant_isolation_policy ON time_entries
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE time_entries FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE time_entries TO nce_app;
    END IF;
END $$;

ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON employees;
CREATE POLICY tenant_isolation_policy ON employees
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE employees FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE employees TO nce_app;
    END IF;
END $$;

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE skills FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON skills;
CREATE POLICY tenant_isolation_policy ON skills
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE skills FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE skills TO nce_app;
    END IF;
END $$;

ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE certifications FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON certifications;
CREATE POLICY tenant_isolation_policy ON certifications
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE certifications FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE certifications TO nce_app;
    END IF;
END $$;

ALTER TABLE absences ENABLE ROW LEVEL SECURITY;
ALTER TABLE absences FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON absences;
CREATE POLICY tenant_isolation_policy ON absences
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE absences FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE absences TO nce_app;
    END IF;
END $$;

ALTER TABLE case_studies ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_studies FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON case_studies;
CREATE POLICY tenant_isolation_policy ON case_studies
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE case_studies FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE case_studies TO nce_app;
    END IF;
END $$;

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON testimonials;
CREATE POLICY tenant_isolation_policy ON testimonials
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE testimonials FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE testimonials TO nce_app;
    END IF;
END $$;

ALTER TABLE content_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_assets FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON content_assets;
CREATE POLICY tenant_isolation_policy ON content_assets
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE content_assets FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE content_assets TO nce_app;
    END IF;
END $$;

ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON resources;
CREATE POLICY tenant_isolation_policy ON resources
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE resources FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE resources TO nce_app;
    END IF;
END $$;

ALTER TABLE allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE allocations FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON allocations;
CREATE POLICY tenant_isolation_policy ON allocations
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE allocations FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE allocations TO nce_app;
    END IF;
END $$;

ALTER TABLE travel_legs ENABLE ROW LEVEL SECURITY;
ALTER TABLE travel_legs FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON travel_legs;
CREATE POLICY tenant_isolation_policy ON travel_legs
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE travel_legs FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE travel_legs TO nce_app;
    END IF;
END $$;

ALTER TABLE stays ENABLE ROW LEVEL SECURITY;
ALTER TABLE stays FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON stays;
CREATE POLICY tenant_isolation_policy ON stays
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE stays FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stays TO nce_app;
    END IF;
END $$;

ALTER TABLE per_diems ENABLE ROW LEVEL SECURITY;
ALTER TABLE per_diems FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON per_diems;
CREATE POLICY tenant_isolation_policy ON per_diems
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE per_diems FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE per_diems TO nce_app;
    END IF;
END $$;

ALTER TABLE portal_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_users FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS external_isolation_policy ON portal_users;
CREATE POLICY external_isolation_policy ON portal_users
    FOR ALL TO nce_app
    USING (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    )
    WITH CHECK (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    );

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE portal_users FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE portal_users TO nce_app;
    END IF;
END $$;

ALTER TABLE portal_document_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_document_shares FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS external_isolation_policy ON portal_document_shares;
CREATE POLICY external_isolation_policy ON portal_document_shares
    FOR ALL TO nce_app
    USING (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    )
    WITH CHECK (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    );

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE portal_document_shares FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE portal_document_shares TO nce_app;
    END IF;
END $$;

ALTER TABLE portal_service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_service_requests FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS external_isolation_policy ON portal_service_requests;
CREATE POLICY external_isolation_policy ON portal_service_requests
    FOR ALL TO nce_app
    USING (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    )
    WITH CHECK (
        namespace_id IS NOT NULL
        AND namespace_id = get_nce_namespace()
        AND customer_scope_id IS NOT NULL
        AND customer_scope_id = get_nce_external_scope()
    );

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE portal_service_requests FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE portal_service_requests TO nce_app;
    END IF;
END $$;

ALTER TABLE business_insights_kpi_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_insights_kpi_snapshots FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON business_insights_kpi_snapshots;
CREATE POLICY tenant_isolation_policy ON business_insights_kpi_snapshots
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE business_insights_kpi_snapshots FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE business_insights_kpi_snapshots TO nce_app;
    END IF;
END $$;

ALTER TABLE procurement_po_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE procurement_po_lines FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON procurement_po_lines;
CREATE POLICY tenant_isolation_policy ON procurement_po_lines
    FOR ALL TO nce_app
    USING  (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE procurement_po_lines FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE procurement_po_lines TO nce_app;
    END IF;
END $$;

COMMENT ON TABLE procurement_po_lines IS
'Procurement purchase order lines content store and status state machine (Wave PR-2). Isolates per tenant namespace via FORCE RLS.';

ALTER TABLE decision_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE decision_feedback FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON decision_feedback;
CREATE POLICY tenant_isolation_policy ON decision_feedback
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE decision_feedback FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE decision_feedback TO nce_app;
    END IF;
END $$;

ALTER TABLE signing_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE signing_credentials FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON signing_credentials;
CREATE POLICY tenant_isolation_policy ON signing_credentials
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE signing_credentials FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE signing_credentials TO nce_app;
    END IF;
END $$;

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON notifications;
CREATE POLICY tenant_isolation_policy ON notifications
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE notifications FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notifications TO nce_app;
    END IF;
END $$;

ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON reminders;
CREATE POLICY tenant_isolation_policy ON reminders
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE reminders FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reminders TO nce_app;
    END IF;
END $$;

ALTER TABLE notification_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_subscriptions FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON notification_subscriptions;
CREATE POLICY tenant_isolation_policy ON notification_subscriptions
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE notification_subscriptions FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notification_subscriptions TO nce_app;
    END IF;
END $$;

ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON documents;
CREATE POLICY tenant_isolation_policy ON documents
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE documents FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE documents TO nce_app;
    END IF;
END $$;

ALTER TABLE document_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_links FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON document_links;
CREATE POLICY tenant_isolation_policy ON document_links
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE document_links FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE document_links TO nce_app;
    END IF;
END $$;

ALTER TABLE document_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_shares FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON document_shares;
CREATE POLICY tenant_isolation_policy ON document_shares
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE document_shares FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE document_shares TO nce_app;
    END IF;
END $$;

ALTER TABLE legal_entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE legal_entities FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_policy ON legal_entities;
CREATE POLICY tenant_isolation_policy ON legal_entities
    FOR ALL TO nce_app
    USING (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace())
    WITH CHECK (namespace_id IS NOT NULL AND namespace_id = get_nce_namespace());

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE legal_entities FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE legal_entities TO nce_app;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE geodata_osm_elements FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE geodata_osm_elements TO nce_app;
        GRANT USAGE, SELECT ON SEQUENCE geodata_osm_elements_id_seq TO nce_app;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nce_app') THEN
        REVOKE ALL ON TABLE geodata_n50_land_cover FROM nce_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE geodata_n50_land_cover TO nce_app;
        GRANT USAGE, SELECT ON SEQUENCE geodata_n50_land_cover_id_seq TO nce_app;
    END IF;
END $$;