"""nce.vertical_modules.sites.service — Domain operations for C17 Site Master Data.

Phase A Wave A-9:
The register's own CRUD (register/list/archive/cadastre lookup/vessel telemetry)
is generated by the C12 resource surface from ``resources.py``'s ``SITE_SPEC`` and
never called through here. What remains is the read/write pair
``address_registry.py``'s Kartverket enrichment (the one hand-written tool the
resource surface does not generate) needs against the register's own row -- see
``mcp_handlers.py``'s module docstring.
Multi-tenant isolated and RLS protected.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from nce.vertical_modules.sites.models import SiteItem, SiteUpdate

# In-memory store for hermetic unit testing and offline execution:
# _MEM_SITES[ns_str][site_id_str] = SiteItem
_MEM_SITES: dict[str, dict[str, SiteItem]] = {}


def _clear_mem_store() -> None:
    """Clear in-memory storage for hermetic test execution."""
    _MEM_SITES.clear()


def normalize_cadastre_id(val: str | None) -> str | None:
    """Normalize cadastre_id (strip whitespace, clean string)."""
    if not val:
        return None
    cleaned = str(val).strip()
    return cleaned if cleaned else None


def _row_to_site_item(row: Any) -> SiteItem:
    def _parse_json(v: Any) -> Any:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except Exception:
                return v
        return v or {}

    return SiteItem(
        id=row["id"] if isinstance(row["id"], UUID) else UUID(str(row["id"])),
        namespace_id=(
            row["namespace_id"]
            if isinstance(row["namespace_id"], UUID)
            else UUID(str(row["namespace_id"]))
        ),
        name=row["name"],
        cadastre_id=row["cadastre_id"],
        site_type=row["site_type"],
        address=_parse_json(row["address"]),
        latitude=row["latitude"],
        longitude=row["longitude"],
        altitude=row["altitude"],
        height=row["height"],
        footprint_geometry=_parse_json(row["footprint_geometry"]),
        telemetry_stream=(
            _parse_json(row["telemetry_stream"]) if row["telemetry_stream"] is not None else None
        ),
        metadata=_parse_json(row["metadata"]),
        archived=row["archived"],
        created_at=row["created_at"],
        updated_at=row["updated_at"],
    )


async def get_site(
    conn: Any,
    namespace_id: UUID | str,
    site_id: UUID | str,
) -> SiteItem | None:
    """Retrieve a site by primary key with tenant isolation."""
    ns_uuid = UUID(str(namespace_id))
    s_uuid = UUID(str(site_id))

    if conn is not None:
        query = """
            SELECT id, namespace_id, name, cadastre_id, site_type,
                   address, latitude, longitude, altitude, height,
                   footprint_geometry, telemetry_stream, metadata,
                   archived, created_at, updated_at
            FROM sites
            WHERE namespace_id = $1 AND id = $2 AND NOT archived
        """
        row = await conn.fetchrow(query, ns_uuid, s_uuid)
        if not row:
            return None
        return _row_to_site_item(row)

    ns_key = str(ns_uuid)
    item = _MEM_SITES.get(ns_key, {}).get(str(s_uuid))
    if item and not item.archived:
        return item
    return None


async def update_site(
    conn: Any,
    namespace_id: UUID | str,
    site_id: UUID | str,
    updates: SiteUpdate | dict[str, Any],
) -> SiteItem | None:
    """Update site attributes."""
    ns_uuid = UUID(str(namespace_id))
    s_uuid = UUID(str(site_id))
    data = updates if isinstance(updates, SiteUpdate) else SiteUpdate(**updates)
    now = datetime.now(timezone.utc)

    existing = await get_site(conn, ns_uuid, s_uuid)
    if not existing:
        return None

    new_cadastre = (
        normalize_cadastre_id(data.cadastre_id)
        if data.cadastre_id is not None
        else existing.cadastre_id
    )

    if conn is not None:
        query = """
            UPDATE sites
            SET name = COALESCE($3, name),
                cadastre_id = COALESCE($4, cadastre_id),
                site_type = COALESCE($5, site_type),
                address = CASE WHEN $6::jsonb IS NOT NULL THEN $6::jsonb ELSE address END,
                latitude = COALESCE($7, latitude),
                longitude = COALESCE($8, longitude),
                altitude = COALESCE($9, altitude),
                height = COALESCE($10, height),
                footprint_geometry = CASE WHEN $11::jsonb IS NOT NULL THEN $11::jsonb ELSE footprint_geometry END,
                telemetry_stream = CASE WHEN $12::jsonb IS NOT NULL THEN $12::jsonb ELSE telemetry_stream END,
                metadata = CASE WHEN $13::jsonb IS NOT NULL THEN $13::jsonb ELSE metadata END,
                archived = COALESCE($14, archived),
                updated_at = $15
            WHERE namespace_id = $1 AND id = $2
            RETURNING id, namespace_id, name, cadastre_id, site_type,
                      address, latitude, longitude, altitude, height,
                      footprint_geometry, telemetry_stream, metadata,
                      archived, created_at, updated_at
        """
        row = await conn.fetchrow(
            query,
            ns_uuid,
            s_uuid,
            data.name,
            new_cadastre,
            data.site_type,
            json.dumps(data.address) if data.address is not None else None,
            data.latitude,
            data.longitude,
            data.altitude,
            data.height,
            json.dumps(data.footprint_geometry) if data.footprint_geometry is not None else None,
            json.dumps(data.telemetry_stream) if data.telemetry_stream is not None else None,
            json.dumps(data.metadata) if data.metadata is not None else None,
            data.archived,
            now,
        )
        if not row:
            return None
        return _row_to_site_item(row)

    # In-memory update
    ns_key = str(ns_uuid)
    item = _MEM_SITES[ns_key][str(s_uuid)]
    updated = SiteItem(
        id=item.id,
        namespace_id=item.namespace_id,
        name=data.name if data.name is not None else item.name,
        cadastre_id=new_cadastre,
        site_type=data.site_type if data.site_type is not None else item.site_type,
        address=data.address if data.address is not None else item.address,
        latitude=data.latitude if data.latitude is not None else item.latitude,
        longitude=data.longitude if data.longitude is not None else item.longitude,
        altitude=data.altitude if data.altitude is not None else item.altitude,
        height=data.height if data.height is not None else item.height,
        footprint_geometry=(
            data.footprint_geometry
            if data.footprint_geometry is not None
            else item.footprint_geometry
        ),
        telemetry_stream=(
            data.telemetry_stream if data.telemetry_stream is not None else item.telemetry_stream
        ),
        metadata=data.metadata if data.metadata is not None else item.metadata,
        archived=data.archived if data.archived is not None else item.archived,
        created_at=item.created_at,
        updated_at=now,
    )
    _MEM_SITES[ns_key][str(s_uuid)] = updated
    return updated
