#!/usr/bin/env python3
"""Assert the runtime image, the lock's compile Python, and the CI matrix agree.

These three drifted apart silently and it cost real damage:

* ``deploy/multiuser/Dockerfile`` runs **python:3.12**-slim-bookworm.
* ``requirements.lock`` was compiled under **3.11**, because ci.yml's verify step pinned
  3.11 to match *the runner* rather than the runtime. A 3.11 resolve cannot see any
  distribution requiring >=3.12, so it silently capped ``numpy`` at 2.4.6 and ``scipy``
  at 1.17.1 while the containers ran 2.5.3 and 1.18.1. The gate reported the lock
  "current" throughout, because it was consistent with the declared floors -- just not
  with the platform that installs them.
* the unit matrix tested 3.10 and 3.11 only, so **the interpreter production runs was the
  one version CI never exercised**.

All three are aligned now. This script keeps them that way, because the invariant is
otherwise enforced by nothing but three comments in three files.

Exits non-zero with a specific diff on drift. No network, no database, no image build.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCKERFILE = ROOT / "deploy" / "multiuser" / "Dockerfile"
LOCK = ROOT / "requirements.lock"
CI = ROOT / ".github" / "workflows" / "ci.yml"


def dockerfile_python() -> str:
    """The runtime image's Python, from the last FROM python:X.Y-... line."""
    versions = re.findall(
        r"^FROM\s+python:(\d+\.\d+)", DOCKERFILE.read_text(encoding="utf-8"), re.MULTILINE
    )
    if not versions:
        raise SystemExit(f"{DOCKERFILE}: no 'FROM python:X.Y' found")
    if len(set(versions)) != 1:
        raise SystemExit(
            f"{DOCKERFILE}: builder and runtime stages disagree on Python: {sorted(set(versions))}"
        )
    return versions[0]


def lock_python() -> str:
    """The Python pip-compile recorded in the lock header."""
    match = re.search(
        r"autogenerated by pip-compile with Python (\d+\.\d+)",
        LOCK.read_text(encoding="utf-8"),
    )
    if not match:
        raise SystemExit(f"{LOCK}: header does not record a pip-compile Python version")
    return match.group(1)


def ci_matrix_versions() -> list[str]:
    """The unit-test matrix's Python versions."""
    match = re.search(r"python-version:\s*\[([^\]]+)\]", CI.read_text(encoding="utf-8"))
    if not match:
        raise SystemExit(f"{CI}: no unit-test matrix python-version list found")
    return re.findall(r"\d+\.\d+", match.group(1))


def main() -> None:
    runtime = dockerfile_python()
    lock = lock_python()
    matrix = ci_matrix_versions()
    problems: list[str] = []

    if lock != runtime:
        problems.append(
            f"requirements.lock was compiled under Python {lock} but the runtime image is "
            f"{runtime}. The lock cannot represent the deployed set: any distribution "
            f"requiring >={runtime} is invisible to a {lock} resolve. Recompile with "
            f"`python scripts/compile_requirements.py --upgrade` under {runtime}."
        )

    if runtime not in matrix:
        problems.append(
            f"the runtime image runs Python {runtime}, which is NOT in the unit-test "
            f"matrix {matrix}. The interpreter production runs would be untested. Add "
            f"{runtime} to the matrix in .github/workflows/ci.yml."
        )

    if problems:
        print("Python platform coupling FAILED:\n", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}\n", file=sys.stderr)
        raise SystemExit(1)

    print(
        f"Python platform coupling OK: runtime image {runtime}, "
        f"lock compiled under {lock}, unit matrix {matrix}."
    )


if __name__ == "__main__":
    main()
