#!/usr/bin/env python
"""Generate docs/_generated/resource_surface.md from declared ResourceSpecs.

Phase A Wave A-1:
Renders the complete inventory of C12 generated resource surfaces directly
from code, documenting REST routes, MCP tools, filtering capabilities, and
tier redaction rules across all vertical engines.

Usage:
    python scripts/gen_resource_surface.py           # write docs/_generated/resource_surface.md
    python scripts/gen_resource_surface.py --check   # exit 1 if file is stale
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys

# Ensure NCE_MASTER_KEY exists for CLI execution
os.environ.setdefault("NCE_MASTER_KEY", "x" * 32)

_ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

_DOC = _ROOT / "docs" / "_generated" / "resource_surface.md"


def generate() -> str:
    from nce.resource_surface import get_all_resource_specs, load_all_engine_resources

    load_all_engine_resources()
    specs = sorted(get_all_resource_specs(), key=lambda s: (s.engine, s.entity))

    lines: list[str] = [
        "# C12 Resource Surface Manifest",
        "",
        "_Generated by `scripts/gen_resource_surface.py` — do not edit by hand._",
        "_Regenerate after adding or modifying any ResourceSpec: `python scripts/gen_resource_surface.py`._",
        "",
        f"Total Declared Resources: **{len(specs)}**",
        "",
        "| Engine | Entity | Node Type | Table Source | REST Collection | MCP Tools | Filterable Fields |",
        "|---|---|---|---|---|---|---|",
    ]

    for s in specs:
        table_str = f"`{s.table_name}`" if s.table_name else "*(graph)*"
        filters_str = (
            ", ".join(f"`{f}`" for f in s.filterable_fields) if s.filterable_fields else "*(none)*"
        )
        mcp_tools_str = f"`{s.engine}_list_{s.mcp_slug}`, `{s.engine}_get_{s.mcp_slug}`, `{s.engine}_upsert_{s.mcp_slug}`, `{s.engine}_archive_{s.mcp_slug}`"
        lines.append(
            f"| **{s.engine}** | `{s.entity}` | `{s.node_type}` | {table_str} | `{s.rest_collection_path}` | {mcp_tools_str} | {filters_str} |"
        )

    lines.extend(
        [
            "",
            "## Standard Verbs & Route Endpoints",
            "",
            "For each resource above, the factory mounts:",
            "",
            "- `GET /api/{engine}/{entity}` — List with `q` search, filters, `sort`, cursor pagination, and `fields` allow-list",
            "- `GET /api/{engine}/{entity}/{id}` — Detail read with C3/C8 principal tier redaction",
            "- `POST /api/{engine}/{entity}` — Create instance (validated against `writable_fields`)",
            "- `PATCH /api/{engine}/{entity}/{id}` — Update instance with `If-Match` / `expected_version` concurrency (409 on conflict)",
            "- `POST /api/{engine}/{entity}/{id}/archive` — Soft archive",
            "- `POST /api/{engine}/{entity}/{id}/restore` — Soft restore",
            "- `GET /api/{engine}/{entity}/{id}/events` — Correlated audit timeline from `event_log`",
            "- `GET|POST /api/{engine}/{entity}/{id}/comments` — Append-only comments log",
            "- `GET|POST|DELETE /api/{engine}/{entity}/{id}/tags` — Resource tags management",
            "- `POST /api/{engine}/{entity}/bulk` — Bulk batch create/update",
            "",
            "## Standard MCP Twin Tools",
            "",
            "- `{engine}_list_{entity}` — Query collection with filters, search, and cursor",
            "- `{engine}_get_{entity}` — Fetch single resource by ID",
            "- `{engine}_upsert_{entity}` — Create or update resource with optimistic concurrency check",
            "- `{engine}_archive_{entity}` — Soft archive resource",
            "",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 if docs are stale")
    args = parser.parse_args()

    content = generate()
    _DOC.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        if not _DOC.exists():
            print(
                f"FAIL: {_DOC} does not exist. Run scripts/gen_resource_surface.py", file=sys.stderr
            )
            return 1
        current = _DOC.read_text(encoding="utf-8")
        if current.strip() != content.strip():
            print(f"FAIL: {_DOC} is stale. Run scripts/gen_resource_surface.py", file=sys.stderr)
            return 1
        print("OK: resource_surface.md is current.")
        return 0

    _DOC.write_text(content, encoding="utf-8")
    print(f"Wrote {len(content)} bytes to {_DOC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
