#!/usr/bin/env python
"""Generate ``docs/API.md`` from NCE's two API surfaces.

NCE exposes capabilities as a REST/HTTP API (the admin Starlette app — callable
with no AI model) and as MCP tools (the agent surface). This script renders both
from the live code so the docs cannot drift:

  - REST endpoints   from ``nce.admin_app.build_admin_routes()``
  - MCP tools        from ``nce.tool_registry.TOOL_REGISTRY``

Usage::

    python scripts/gen_api_docs.py            # write docs/API.md
    python scripts/gen_api_docs.py --check     # exit 1 if docs/API.md is stale

The ``--check`` mode backs the drift gate in ``tests/test_api_docs_current.py``,
which runs in CI so the API docs stay current on every merge.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

_ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

_DOC = _ROOT / "docs" / "API.md"


def _flag(value: object) -> str:
    return "yes" if value else ""


def generate() -> str:
    from starlette.routing import Route

    from nce.admin_app import build_admin_routes
    from nce.tool_registry import TOOL_REGISTRY

    lines: list[str] = [
        "# NCE API",
        "",
        "_Generated by `scripts/gen_api_docs.py` — do not edit by hand._",
        "_Regenerate after changing any route or tool: `python scripts/gen_api_docs.py`._",
        "",
        "## REST endpoints (HTTP — no AI model required)",
        "",
        "Served by the admin Starlette app (HMAC/mTLS auth). Callable by any HTTP client",
        "(the BFF, scripts, cron) without an LLM.",
        "",
        "| Method | Path | Handler |",
        "|---|---|---|",
    ]
    rest_rows: list[tuple[str, str, str]] = []
    for route in build_admin_routes():
        if isinstance(route, Route):
            methods = ",".join(sorted(m for m in (route.methods or set()) if m != "HEAD"))
            handler = getattr(route.endpoint, "__name__", str(route.endpoint))
            rest_rows.append((methods or "GET", route.path, handler))
    for method, path, handler in sorted(rest_rows, key=lambda r: (r[1], r[0])):
        lines.append(f"| {method} | `{path}` | `{handler}` |")

    lines += [
        "",
        "## MCP tools (agent surface)",
        "",
        "Dispatched via the MCP JSON-RPC server. Gating columns drive dispatch behavior.",
        "",
        "| Tool | admin_only | mutation | cacheable | migration |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(TOOL_REGISTRY):
        spec = TOOL_REGISTRY[name]
        lines.append(
            f"| `{name}` | {_flag(spec.admin_only)} | {_flag(spec.mutation)} "
            f"| {_flag(spec.cacheable)} | {_flag(spec.migration)} |"
        )

    lines += [
        "",
        f"_Totals: {len(rest_rows)} REST endpoints, {len(TOOL_REGISTRY)} MCP tools._",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if docs/API.md is stale")
    args = parser.parse_args()

    content = generate()
    if args.check:
        existing = _DOC.read_text(encoding="utf-8") if _DOC.exists() else ""
        if existing.strip() != content.strip():
            print(
                "docs/API.md is stale — regenerate with: python scripts/gen_api_docs.py",
                file=sys.stderr,
            )
            return 1
        return 0

    _DOC.write_text(content, encoding="utf-8")
    print(f"wrote {_DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
