#!/usr/bin/env python3
"""Engine Inventory Figures Generator (Wave D-GEN).

Eliminates hand-maintenance of the three core engine counters:
1. TOOL_REGISTRY entries: extracted via AST from nce/tool_registry.py and validated
   against _EXPECTED_TOTAL in tests/test_tool_registry.py. Categorised into shared vs.
   per-engine modules under nce/vertical_modules/.
2. SQL migrations: scanned from nce/migrations/ (base migrations 001 -> max prefix)
   and nce/migrations/optional/, reporting total files, prefix span, and unallocated gaps.
3. Golden Thread seam burndown: read directly from docs/_generated/golden_thread_seams.md
   (generated by scripts/gen_golden_thread_seams.py from strict xfails in
   tests/integration/test_golden_thread.py).

Outputs:
- docs/_generated/engine_figures.md: Authoritative generated markdown inventory.
- Mechanically updates docs/vertical_engines/ENGINE_STATUS.md when --update-status is passed.
- Supports --check mode to gate freshness in CI and pre-commit workflows.
"""

from __future__ import annotations

import argparse
import ast
import datetime
import pathlib
import re
import subprocess
import sys
from typing import Any, Final

_ENGINE_STATUS_TOOLS_RE: Final[re.Pattern[str]] = re.compile(
    r"\|\s*`TOOL_REGISTRY` entries\s*\|\s*\*\*(\d+)\*\*\s+MCP tools"
)
_ENGINE_STATUS_MAX_MIGRATION_RE: Final[re.Pattern[str]] = re.compile(
    r"\|\s*SQL migrations\s*\|\s*.*?`001`\s*→\s*`(\d{3})`"
)
_ENGINE_STATUS_GOLDEN_THREAD_RE: Final[re.Pattern[str]] = re.compile(
    r"\|\s*Golden Thread seam burndown\s*\|\s*\*\*(\d+)\s+of\s+(\d+)\*\*\s+lifecycle steps broken"
)
_GOLDEN_THREAD_SUMMARY_RE: Final[re.Pattern[str]] = re.compile(
    r"##\s*Summary\s*—\s*(\d+)\s+of\s+(\d+)\s+lifecycle steps broken,\s*(\d+)\s+distinct seam"
)


def git_rev_parse(repo: str, ref: str = "HEAD") -> str:
    """Return short commit SHA for a ref."""
    try:
        res = subprocess.run(
            ["git", "-C", repo, "rev-parse", "--short", ref],
            capture_output=True,
            text=True,
            check=True,
            encoding="utf-8",
        )
        return res.stdout.strip()
    except Exception:
        return ref


def git_ls_tree(repo: str, baseline: str, path: str = "") -> list[str]:
    """List paths in git tree at baseline."""
    cmd = ["git", "-C", repo, "ls-tree", "-r", "--name-only", baseline]
    if path:
        cmd.extend(["--", path])
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True, encoding="utf-8")
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]
    except Exception:
        target = pathlib.Path(repo) / path if path else pathlib.Path(repo)
        if target.is_dir():
            return [
                str(p.relative_to(pathlib.Path(repo))).replace("\\", "/")
                for p in target.rglob("*")
                if p.is_file()
            ]
        return []


def git_show(repo: str, baseline: str, path: str) -> str:
    """Read file content from git tree or filesystem fallback."""
    try:
        cmd = ["git", "-C", repo, "show", f"{baseline}:{path}"]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True, encoding="utf-8")
        return result.stdout
    except Exception:
        file_path = pathlib.Path(repo) / path
        return file_path.read_text(encoding="utf-8", errors="replace")


def discover_vertical_engines(repo: str, baseline: str) -> list[str]:
    """Discover all packages under nce/vertical_modules/."""
    paths = git_ls_tree(repo, baseline, "nce/vertical_modules/")
    engines: set[str] = set()
    for path in paths:
        parts = path.split("/")
        if len(parts) >= 3 and parts[0] == "nce" and parts[1] == "vertical_modules":
            if not parts[2].endswith(".py"):
                engines.add(parts[2])
    return sorted(engines)


def get_import_map(code: str) -> dict[str, str]:
    """Parse AST import statements to map aliases/names to module paths."""
    tree = ast.parse(code)
    import_map: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.ImportFrom):
            mod = node.module or ""
            for alias in node.names:
                name = alias.asname or alias.name
                import_map[name] = f"{mod}.{alias.name}" if mod else alias.name
        elif isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.asname or alias.name
                import_map[name] = alias.name
    return import_map


def extract_tool_registry_stats(repo: str, baseline: str) -> dict[str, Any]:
    """Extract tool counts from nce/tool_registry.py AST and tests/test_tool_registry.py."""
    code = git_show(repo, baseline, "nce/tool_registry.py")
    import_map = get_import_map(code)
    tree = ast.parse(code)
    vertical_engines = discover_vertical_engines(repo, baseline)

    tools: list[dict[str, Any]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "TOOL_REGISTRY":
            if isinstance(node.value, ast.Dict):
                for k, v in zip(node.value.keys, node.value.values):
                    if isinstance(k, ast.Constant) and isinstance(k.value, str):
                        tool_name = k.value
                        flags: list[str] = []
                        handler_module: str | None = None
                        if isinstance(v, ast.Call):
                            for arg in v.args:
                                if (
                                    isinstance(arg, ast.Call)
                                    and getattr(arg.func, "id", None) == "_h"
                                ):
                                    if arg.args:
                                        first_arg = arg.args[0]
                                        if isinstance(first_arg, ast.Name):
                                            handler_module = first_arg.id
                                        elif isinstance(first_arg, ast.Attribute):
                                            if isinstance(first_arg.value, ast.Name):
                                                handler_module = first_arg.value.id
                            for kw in v.keywords:
                                if getattr(kw.value, "value", False) is True:
                                    flags.append(kw.arg)

                        resolved_path = import_map.get(handler_module, handler_module or "")

                        assigned_engine = "shared"
                        for eng in vertical_engines:
                            if (
                                f"vertical_modules.{eng}" in resolved_path
                                or f"vertical_modules/{eng}" in resolved_path
                            ):
                                assigned_engine = eng
                                break

                        if assigned_engine == "shared":
                            if tool_name.startswith("diag_"):
                                assigned_engine = "diagnostics"
                            elif tool_name.startswith("d365_"):
                                assigned_engine = "dynamics365"
                            elif tool_name.startswith("netbox_"):
                                assigned_engine = "netbox"

                        tools.append(
                            {
                                "name": tool_name,
                                "engine": assigned_engine,
                                "flags": flags,
                            }
                        )

    test_code = git_show(repo, baseline, "tests/test_tool_registry.py")
    test_tree = ast.parse(test_code)
    expected_total: int | None = None
    for node in ast.walk(test_tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "_EXPECTED_TOTAL":
                    if isinstance(node.value, ast.Constant) and isinstance(node.value.value, int):
                        expected_total = node.value.value

    shared_tools = [t for t in tools if t["engine"] == "shared"]
    engine_tools = [t for t in tools if t["engine"] != "shared"]
    per_engine: dict[str, int] = {}
    for t in engine_tools:
        per_engine[t["engine"]] = per_engine.get(t["engine"], 0) + 1

    return {
        "total_tools": len(tools),
        "expected_total": expected_total,
        "shared_count": len(shared_tools),
        "engine_count": len(engine_tools),
        "num_engines": len(per_engine),
        "per_engine": dict(sorted(per_engine.items())),
    }


def extract_migration_stats(repo: str, baseline: str) -> dict[str, Any]:
    """Scan nce/migrations/ and nce/migrations/optional/ for migration figures."""
    all_files = git_ls_tree(repo, baseline, "nce/migrations/")
    base_migrations: list[str] = []
    optional_migrations: list[str] = []

    for f in all_files:
        filename = f.split("/")[-1]
        if f.startswith("nce/migrations/optional/") and filename.endswith(".sql"):
            optional_migrations.append(filename)
        elif (
            f.startswith("nce/migrations/")
            and "/" not in f[len("nce/migrations/") :]
            and filename.endswith(".sql")
        ):
            if re.match(r"^\d{3}_", filename):
                base_migrations.append(filename)

    prefix_nums = sorted([int(m[:3]) for m in base_migrations])
    min_prefix = f"{min(prefix_nums):03d}" if prefix_nums else "000"
    max_prefix = f"{max(prefix_nums):03d}" if prefix_nums else "000"

    all_expected = set(range(int(min_prefix), int(max_prefix) + 1))
    missing_nums = sorted(list(all_expected - set(prefix_nums)))
    gaps_str = ", ".join(f"`{n:03d}`" for n in missing_nums)

    return {
        "base_count": len(base_migrations),
        "optional_count": len(optional_migrations),
        "total_count": len(base_migrations) + len(optional_migrations),
        "min_prefix": min_prefix,
        "max_prefix": max_prefix,
        "missing_prefixes": missing_nums,
        "gaps_str": gaps_str,
        "optional_files": optional_migrations,
    }


def extract_golden_thread_stats(repo: str, baseline: str) -> dict[str, Any]:
    """Read Golden Thread seam status from docs/_generated/golden_thread_seams.md."""
    content = git_show(repo, baseline, "docs/_generated/golden_thread_seams.md")
    m = _GOLDEN_THREAD_SUMMARY_RE.search(content)
    if not m:
        m2 = re.search(r"(\d+)\s+of\s+(\d+)\s+lifecycle steps broken", content)
        if m2:
            return {
                "broken": int(m2.group(1)),
                "total_steps": int(m2.group(2)),
                "distinct_seams": 0,
            }
        raise ValueError("Could not parse summary line from docs/_generated/golden_thread_seams.md")

    return {
        "broken": int(m.group(1)),
        "total_steps": int(m.group(2)),
        "distinct_seams": int(m.group(3)),
    }


def generate_markdown(
    baseline_sha: str,
    tool_stats: dict[str, Any],
    mig_stats: dict[str, Any],
    gt_stats: dict[str, Any],
) -> str:
    """Generate docs/_generated/engine_figures.md content."""
    lines: list[str] = [
        f"> **Status:** shipped · **Verified-against:** `{baseline_sha}` (public `main`) · **Last-audited:** generated",
        "",
        "# NCE Engine Figures — Inventory & Counters",
        "",
        "> **This page is generated by `scripts/gen_engine_figures.py` — it cannot go stale.**",
        "> It provides the single source of truth for repository engine metrics, consumed by",
        "> [`docs/vertical_engines/ENGINE_STATUS.md`](../vertical_engines/ENGINE_STATUS.md) and CI ratchets.",
        "> Regenerate with:",
        "> ```bash",
        "> python scripts/gen_engine_figures.py --repo . --baseline HEAD --out docs/_generated/engine_figures.md --update-status docs/vertical_engines/ENGINE_STATUS.md",
        "> ```",
        "",
        "## Executive Summary",
        "",
        "| Counter | Value | Source of Truth |",
        "|---|---|---|",
        f"| `TOOL_REGISTRY` entries | **{tool_stats['total_tools']}** MCP tools ({tool_stats['shared_count']} shared + {tool_stats['engine_count']} across {tool_stats['num_engines']} engines) | AST of [`nce/tool_registry.py`](../../nce/tool_registry.py), pinned by `_EXPECTED_TOTAL = {tool_stats['expected_total']}` in [`tests/test_tool_registry.py`](../../tests/test_tool_registry.py) |",
        f"| SQL migrations | {mig_stats['base_count']} files (+{mig_stats['optional_count']} optional), `{mig_stats['min_prefix']}` → `{mig_stats['max_prefix']}` — gaps at {mig_stats['gaps_str']} | Files in [`nce/migrations/`](../../nce/migrations/) and [`nce/migrations/optional/`](../../nce/migrations/optional/) |",
        f"| Golden Thread seam burndown | **{gt_stats['broken']} of {gt_stats['total_steps']}** lifecycle steps broken ({gt_stats['distinct_seams']} distinct seams) | Generated in [`docs/_generated/golden_thread_seams.md`](golden_thread_seams.md) from [`tests/integration/test_golden_thread.py`](../../tests/integration/test_golden_thread.py) |",
        "",
        "## Tool Registry Breakdown",
        "",
        f"- **Total Registered Tools:** {tool_stats['total_tools']}",
        f"- **Shared Core Tools:** {tool_stats['shared_count']}",
        f"- **Vertical Engine Tools:** {tool_stats['engine_count']} across {tool_stats['num_engines']} engine packages",
        "",
        "| Engine Package | Tool Count |",
        "|---|---:|",
    ]

    for eng, count in tool_stats["per_engine"].items():
        lines.append(f"| `{eng}` | {count} |")

    lines.extend(
        [
            "",
            "## SQL Migration Census",
            "",
            f"- **Base Migrations:** {mig_stats['base_count']} files (`{mig_stats['min_prefix']}` → `{mig_stats['max_prefix']}`)",
            f"- **Optional Migrations:** {mig_stats['optional_count']} files ({', '.join('`' + f + '`' for f in mig_stats['optional_files'])})",
            f"- **Unallocated / Skipped Prefixes in Base:** {mig_stats['gaps_str']}",
            f"- **Total SQL Migration Files:** {mig_stats['total_count']}",
            "",
            "## Golden Thread Seam Status",
            "",
            f"- **Lifecycle Steps:** {gt_stats['total_steps']}",
            f"- **Broken Steps (strict xfails):** {gt_stats['broken']}",
            f"- **Distinct Open Seams:** {gt_stats['distinct_seams']}",
            "- **Authoritative Seam Report:** [`docs/_generated/golden_thread_seams.md`](golden_thread_seams.md)",
            "",
        ]
    )

    return "\n".join(lines)


def update_engine_status(
    status_text: str,
    baseline_sha: str,
    tool_stats: dict[str, Any],
    mig_stats: dict[str, Any],
    gt_stats: dict[str, Any],
) -> str:
    """Return updated text for docs/vertical_engines/ENGINE_STATUS.md."""
    text = status_text

    text = re.sub(
        r"> \*\*Status:\*\* [^\n]*· \*\*Verified-against:\*\* `[a-f0-9]+`[^\n]*",
        f"> **Status:** shipped · **Verified-against:** `{baseline_sha}` (public `main`) · **Last-audited:** {datetime.date.today().isoformat()}",
        text,
        count=1,
    )

    text = re.sub(
        r"## Measured inventory at `[a-f0-9]+`",
        f"## Measured inventory at `{baseline_sha}`",
        text,
        count=1,
    )

    tool_row = (
        f"| `TOOL_REGISTRY` entries | **{tool_stats['total_tools']}** MCP tools "
        f"({tool_stats['shared_count']} shared + {tool_stats['engine_count']} engine) — "
        f"see [`docs/_generated/engine_figures.md`](../_generated/engine_figures.md) |"
    )
    text = re.sub(
        r"\|\s*`TOOL_REGISTRY` entries\s*\|[^\n]*",
        tool_row,
        text,
        count=1,
    )

    mig_row = (
        f"| SQL migrations | {mig_stats['base_count']} files (+{mig_stats['optional_count']} optional), "
        f"`{mig_stats['min_prefix']}` → `{mig_stats['max_prefix']}` — "
        f"gaps at `002`, `009`, `059` (never allocated); `010` exists only under `nce/migrations/optional/`. — "
        f"see [`docs/_generated/engine_figures.md`](../_generated/engine_figures.md) |"
    )
    text = re.sub(
        r"\|\s*SQL migrations\s*\|[^\n]*",
        mig_row,
        text,
        count=1,
    )

    gt_row = (
        f"| Golden Thread seam burndown | **{gt_stats['broken']} of {gt_stats['total_steps']}** "
        f"lifecycle steps broken ({gt_stats['distinct_seams']} distinct seams) — "
        f"mirrored from [`docs/_generated/golden_thread_seams.md`](../_generated/golden_thread_seams.md); "
        f"see [`docs/_generated/engine_figures.md`](../_generated/engine_figures.md) |"
    )
    text = re.sub(
        r"\|\s*Golden Thread seam burndown\s*\|[^\n]*",
        gt_row,
        text,
        count=1,
    )

    return text


def write_crlf(path: pathlib.Path, content: str) -> None:
    """Write content ensuring strict CRLF line endings."""
    crlf_content = content.replace("\r\n", "\n").replace("\n", "\r\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(crlf_content.encode("utf-8"))


def normalize_volatile(text: str) -> str:
    """Strip volatile headers (commit sha and timestamp) for content drift checks."""
    text = re.sub(
        r">\s*\*\*Status:\*\*.*?·\s*\*\*Verified-against:\*\*.*?·\s*\*\*Last-audited:\*\*.*",
        "",
        text,
    )
    text = re.sub(r"##\s*Measured inventory at `[a-f0-9]+`", "", text)
    return text.strip()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/_generated/engine_figures.md and update ENGINE_STATUS.md"
    )
    parser.add_argument("--repo", default=".", help="Path to NCE git repo")
    parser.add_argument("--baseline", default="HEAD", help="Git baseline ref")
    parser.add_argument(
        "--out",
        default="docs/_generated/engine_figures.md",
        help="Output markdown path for engine figures",
    )
    parser.add_argument(
        "--update-status",
        nargs="?",
        const="docs/vertical_engines/ENGINE_STATUS.md",
        default=None,
        help="Optionally update docs/vertical_engines/ENGINE_STATUS.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify files match generated output without writing (exit 1 on drift)",
    )
    args = parser.parse_args()

    repo = args.repo
    baseline = args.baseline
    baseline_sha = git_rev_parse(repo, baseline)

    tool_stats = extract_tool_registry_stats(repo, baseline)
    mig_stats = extract_migration_stats(repo, baseline)
    gt_stats = extract_golden_thread_stats(repo, baseline)

    if (
        tool_stats["expected_total"] is not None
        and tool_stats["total_tools"] != tool_stats["expected_total"]
    ):
        print(
            f"ERROR: TOOL_REGISTRY size ({tool_stats['total_tools']}) does not match "
            f"_EXPECTED_TOTAL ({tool_stats['expected_total']}) in tests/test_tool_registry.py!",
            file=sys.stderr,
        )
        return 1

    generated_md = generate_markdown(
        baseline_sha=baseline_sha,
        tool_stats=tool_stats,
        mig_stats=mig_stats,
        gt_stats=gt_stats,
    )

    out_path = pathlib.Path(repo) / args.out
    status_path = pathlib.Path(repo) / args.update_status if args.update_status else None

    if args.check:
        drift = False
        if not out_path.exists():
            print(f"CHECK FAILED: {out_path} does not exist.", file=sys.stderr)
            drift = True
        else:
            current_md = out_path.read_text(encoding="utf-8").replace("\r\n", "\n")
            expected_md = generated_md.replace("\r\n", "\n")
            if normalize_volatile(current_md) != normalize_volatile(expected_md):
                print(
                    f"CHECK FAILED: {out_path} has drifted from generated state.", file=sys.stderr
                )
                drift = True

        if status_path and status_path.exists():
            current_status = status_path.read_text(encoding="utf-8").replace("\r\n", "\n")
            expected_status = update_engine_status(
                status_text=current_status,
                baseline_sha=baseline_sha,
                tool_stats=tool_stats,
                mig_stats=mig_stats,
                gt_stats=gt_stats,
            ).replace("\r\n", "\n")
            if normalize_volatile(current_status) != normalize_volatile(expected_status):
                print(
                    f"CHECK FAILED: {status_path} has drifted from generated state.",
                    file=sys.stderr,
                )
                drift = True

        if drift:
            return 1
        print("CHECK PASSED: Engine figures are up to date.")
        return 0

    write_crlf(out_path, generated_md)
    print(
        f"Generated {out_path} (tools: {tool_stats['total_tools']}, migrations: {mig_stats['base_count']}, gt: {gt_stats['broken']}/{gt_stats['total_steps']})"
    )

    if status_path:
        current_status = status_path.read_text(encoding="utf-8")
        new_status = update_engine_status(
            status_text=current_status,
            baseline_sha=baseline_sha,
            tool_stats=tool_stats,
            mig_stats=mig_stats,
            gt_stats=gt_stats,
        )
        write_crlf(status_path, new_status)
        print(f"Updated {status_path} with verified-against `{baseline_sha}`")

    return 0


if __name__ == "__main__":
    sys.exit(main())
