#!/usr/bin/env python3
"""Split ``nce/schema.sql`` into a bootstrap half and a runtime half (Q-4 step 2).

Why
---
``NCEEngine.connect()`` executes the whole of ``schema.sql`` on **every connect**
(``orchestrator.py:205``). Measured on ``1163254``: 697 statements, 127 ``CREATE TABLE``,
168 ``ALTER TABLE``, 84 ``DO`` blocks, 185 ``CREATE INDEX``.

Steps 1/1b/1c established what that actually does, and the answer was not what the charter
row assumed. ``schema.sql`` is not a dead second writer -- its ``DO`` blocks probe
``information_schema`` and add what is missing, and the tenant-isolation loop **drops and
recreates** every policy. It is an *unledgered, self-healing migration runner*.

That is why a naive "run it only on an empty database" flip is wrong, and why this splits
rather than gates. The two halves want opposite treatment:

* **runtime** -- functions, policies, triggers, RLS enablement, grants, extensions, roles.
  Re-asserting these every connect is **how updates propagate to an existing database**
  and how policy drift self-heals. Losing that is a silent regression, so it keeps running.
* **bootstrap** -- ``CREATE TABLE``, ``ADD COLUMN``, ``CREATE INDEX``, ``ADD CONSTRAINT``
  and the backfills. These want to happen once. Migrations own them afterwards.

What this buys, each traceable to a measurement:

1. 168 ``ALTER TABLE`` + backfills stop running on every connect.
2. The tenant-assignment side effect stops. ``UPDATE kg_nodes SET namespace_id =
   global_ns_id WHERE namespace_id IS NULL`` currently runs on **every connect, forever**,
   filing any NULL-namespace row into ``_global_legacy`` with no record. On a multi-tenant
   database that is a data-placement decision taken by a startup path.
3. Structural DDL becomes ledgered -- the original goal of the row.
4. Functions and policies keep propagating, so the WORM guard and the RLS loop stay
   self-healing.

Risk posture
------------
**Bootstrap is the only file where behaviour changes**, because it is the one that stops
running on an existing database. So the classifier is deliberately asymmetric: a statement
goes to bootstrap only when it is *clearly* one-time structural DDL. Everything else --
including anything ambiguous -- stays in runtime, where behaviour is identical to today.
An over-inclusive runtime file costs a few milliseconds per connect; an over-inclusive
bootstrap file silently stops maintaining something.

Equivalence is not assumed. ``--verify`` applies ``bootstrap`` then ``runtime`` to one
database and ``schema.sql`` to another, then compares the resulting catalogues.

Usage::

    python scripts/split_schema.py --out-dir nce/
    python scripts/split_schema.py --check          # do the files on disk match a fresh split?
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCHEMA = _REPO_ROOT / "nce" / "schema.sql"

_BANNER = """-- ============================================================================
-- GENERATED by scripts/split_schema.py from nce/schema.sql -- DO NOT EDIT BY HAND.
--
-- {which}
--
-- {note}
--
-- Regenerate:  python scripts/split_schema.py --out-dir nce/
-- Verify:      python scripts/split_schema.py --check
-- ============================================================================

"""

_BOOTSTRAP_NOTE = (
    "Runs ONLY when `applied_migrations` is empty. On an existing database the numbered\n"
    "-- migration chain owns everything in here. This is the half where behaviour changes,\n"
    "-- so it contains only statements that are unambiguously one-time structural DDL."
)
_RUNTIME_NOTE = (
    "Runs on EVERY connect, exactly as the whole of schema.sql does today. Re-asserting\n"
    "-- these is how function and policy updates reach an existing database, and how the\n"
    "-- tenant-isolation loop self-heals. Anything ambiguous lives here rather than in\n"
    "-- bootstrap, because staying here preserves current behaviour."
)


def split_statements(text: str) -> list[str]:
    """Split SQL on top-level ``;``, respecting ``$tag$`` bodies, strings and comments.

    Verified byte-faithful against ``nce/schema.sql``: rejoining the output reproduces the
    input exactly apart from trailing newlines. A naive split on ``;`` shreds all 84 ``DO``
    blocks, so this is not optional.
    """
    out: list[str] = []
    buf: list[str] = []
    i, n = 0, len(text)
    dollar: str | None = None
    in_str = line_comment = block_comment = False
    while i < n:
        ch = text[i]
        two = text[i : i + 2]
        if line_comment:
            buf.append(ch)
            if ch == "\n":
                line_comment = False
            i += 1
            continue
        if block_comment:
            buf.append(ch)
            if two == "*/":
                buf.append(text[i + 1])
                i += 2
                block_comment = False
                continue
            i += 1
            continue
        if dollar:
            if text.startswith(dollar, i):
                buf.append(text[i : i + len(dollar)])
                i += len(dollar)
                dollar = None
                continue
            buf.append(ch)
            i += 1
            continue
        if in_str:
            buf.append(ch)
            if ch == "'":
                in_str = False
            i += 1
            continue
        if two == "--":
            line_comment = True
            buf.append(ch)
            i += 1
            continue
        if two == "/*":
            block_comment = True
            buf.append(ch)
            i += 1
            continue
        if ch == "'":
            in_str = True
            buf.append(ch)
            i += 1
            continue
        m = re.match(r"\$[A-Za-z_]*\$", text[i:])
        if m:
            dollar = m.group(0)
            buf.append(dollar)
            i += len(dollar)
            continue
        if ch == ";":
            buf.append(ch)
            out.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf)
    if tail.strip():
        out.append(tail)
    return out


def _strip_comments(sql: str) -> str:
    sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.S)
    return re.sub(r"--[^\n]*", " ", sql)


def _strip_dollar_bodies(sql: str) -> str:
    """Blank out ``$tag$ ... $tag$`` bodies of FUNCTION/PROCEDURE definitions only.

    Without this, ``CREATE OR REPLACE FUNCTION nce_ensure_event_log_monthly_partitions``
    classifies as bootstrap, because its *body* contains ``CREATE TABLE`` for the partitions
    it manages. The statement is a function definition; what the function does when called
    is not a schema change made by this file.

    🔴 But this must NOT apply to ``DO`` blocks. For a function the body is a definition;
    for a ``DO`` block **the body is the statement**. Stripping it left the classifier
    looking at ``DO ;`` -- nothing -- so all 84 of them fell through to the runtime default,
    including the one that backfills ``kg_nodes.namespace_id``. That is the single side
    effect this whole split exists to stop, and the first version of this function kept it
    running forever.
    """
    if re.search(r"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:FUNCTION|PROCEDURE)\b", sql, re.I):
        return re.sub(r"(\$[A-Za-z_]*\$).*?\1", " ", sql, flags=re.S)
    return sql


# One-time structural DDL. Matched only outside function bodies.
_BOOTSTRAP = re.compile(
    r"\bCREATE\s+TABLE\b"
    r"|\bADD\s+COLUMN\b"
    r"|\bCREATE\s+(?:UNIQUE\s+)?INDEX\b"
    r"|\bADD\s+CONSTRAINT\b"
    r"|\bALTER\s+COLUMN\b"
    r"|\bDROP\s+COLUMN\b"
    # A DROP must travel with the CREATE it pairs with, or the two halves execute it in the
    # wrong order. schema.sql uses `DROP CONSTRAINT IF EXISTS x; ADD CONSTRAINT x ...` as a
    # recreate idiom. The first version sent the DROP to runtime and the ADD to bootstrap,
    # so bootstrap added the constraint and runtime then dropped it -- 13 constraints and
    # indexes silently absent. `DROP POLICY` and `DROP TRIGGER` stay in runtime for the same
    # reason, paired with their CREATEs.
    r"|\bDROP\s+CONSTRAINT\b"
    r"|^\s*DROP\s+INDEX\b"
    r"|^\s*UPDATE\s"
    r"|^\s*INSERT\s+INTO\b",
    re.I | re.M,
)

# Things whose whole value is being re-asserted. These win ties.
_RUNTIME = re.compile(
    r"\bCREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\b"
    r"|\bCREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\b"
    r"|\bCREATE\s+POLICY\b"
    r"|\bDROP\s+POLICY\b"
    r"|ROW\s+LEVEL\s+SECURITY\b"
    r"|^\s*GRANT\b"
    r"|^\s*REVOKE\b",
    re.I | re.M,
)


def classify(statement: str) -> str:
    """Return ``"bootstrap"`` or ``"runtime"`` for one statement.

    Asymmetric on purpose. A statement reaches ``bootstrap`` only when it looks like
    one-time structural DDL **and** carries no runtime concern. Everything else, including
    anything this does not recognise, stays in ``runtime`` where behaviour is unchanged.
    """
    body = _strip_dollar_bodies(_strip_comments(statement))
    if not body.strip():
        return "runtime"  # a comment-only chunk; harmless either way, keep it adjacent
    if _RUNTIME.search(body):
        return "runtime"
    if _BOOTSTRAP.search(body):
        return "bootstrap"
    return "runtime"


# Prerequisites that the BOOTSTRAP half depends on even though they belong to runtime.
#
# Splitting one file into two reorders execution, and schema.sql's statement order encodes
# dependencies. The first version of this script put `CREATE EXTENSION vector` in runtime
# and `CREATE TABLE memories` -- whose columns use the vector type -- in bootstrap, which
# runs first. Result: 64 errors, starting with `type "halfvec" does not exist`, and 894
# objects missing. The equivalence check caught it; nothing else would have.
#
# These statements are all idempotent (`IF NOT EXISTS`, `OR REPLACE`, or guarded by a
# catalogue probe), so emitting them into BOTH halves is free and removes the ordering
# hazard entirely rather than relying on a hand-maintained phase order.
_PREREQ = re.compile(
    r"^\s*CREATE\s+EXTENSION\b"
    r"|^\s*CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\b"
    r"|\bCREATE\s+ROLE\b"
    r"|\bpg_roles\b"
    r"|^\s*CREATE\s+(?:TYPE|DOMAIN)\b",
    re.I | re.M,
)


def is_prerequisite(statement: str) -> bool:
    """Does the bootstrap half need this even though it is a runtime statement?"""
    body = _strip_comments(statement)
    if re.search(r"\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:FUNCTION|PROCEDURE)\b", body, re.I):
        head = body.split("$", 1)[0]
        return bool(_PREREQ.search(head))
    return bool(_PREREQ.search(body))


def build(schema_path: Path = _SCHEMA) -> tuple[str, str, dict[str, int]]:
    sql = schema_path.read_text(encoding="utf-8", errors="replace")
    statements = split_statements(sql)
    boot: list[str] = []
    run: list[str] = []
    counts = {"bootstrap": 0, "runtime": 0, "total": len(statements), "duplicated_prereq": 0}
    for stmt in statements:
        where = classify(stmt)
        if where == "runtime" and is_prerequisite(stmt):
            # Emitted into both halves; see _PREREQ.
            boot.append(stmt)
            run.append(stmt)
            counts["runtime"] += 1
            counts["duplicated_prereq"] += 1
            continue
        (boot if where == "bootstrap" else run).append(stmt)
        counts[where] += 1
    boot_sql = _BANNER.format(which="BOOTSTRAP half of schema.sql", note=_BOOTSTRAP_NOTE) + "".join(
        boot
    )
    run_sql = _BANNER.format(which="RUNTIME half of schema.sql", note=_RUNTIME_NOTE) + "".join(run)
    return boot_sql, run_sql, counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schema", default=str(_SCHEMA))
    ap.add_argument(
        "--out-dir", default=None, help="write schema_bootstrap.sql / schema_runtime.sql here"
    )
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if the files on disk differ from a fresh split"
    )
    args = ap.parse_args()

    boot_sql, run_sql, counts = build(Path(args.schema))
    print(
        f"{counts['total']} statements -> bootstrap {counts['bootstrap']}, runtime {counts['runtime']}"
    )

    out_dir = Path(args.out_dir) if args.out_dir else Path(args.schema).parent
    boot_path = out_dir / "schema_bootstrap.sql"
    run_path = out_dir / "schema_runtime.sql"

    if args.check:
        drift = False
        for path, expected in ((boot_path, boot_sql), (run_path, run_sql)):
            if not path.exists():
                print(f"CHECK FAILED: {path} does not exist.", file=sys.stderr)
                drift = True
                continue
            actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
            if actual != expected.replace("\r\n", "\n"):
                print(
                    f"CHECK FAILED: {path} differs from a fresh split of schema.sql.",
                    file=sys.stderr,
                )
                print(
                    "  Regenerate: python scripts/split_schema.py --out-dir nce/", file=sys.stderr
                )
                drift = True
        if not drift:
            print("CHECK PASSED: both halves match schema.sql.")
        return 1 if drift else 0

    boot_path.write_text(boot_sql, encoding="utf-8", newline="\n")
    run_path.write_text(run_sql, encoding="utf-8", newline="\n")
    print(f"wrote {boot_path}\nwrote {run_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
