"""Tests for C12 ResourceSpec tool collision guard in nce.tool_registry (Wave A-4b).

Prevents silent overwriting of hand-written MCP tools when a ResourceSpec generates
a colliding tool name (e.g. `resources_list_resources` vs `handle_resources_list_resources`).
"""

from __future__ import annotations

import pytest

from nce.resource_surface import ResourceSpec
from nce.resource_surface.mcp import build_mcp_tool_specs
from nce.tool_registry import TOOL_REGISTRY, ToolSpec


def test_tool_registry_normal_load_has_no_collisions():
    """Under normal operation, all 331 tools are loaded with 0 collisions."""
    assert len(TOOL_REGISTRY) >= 327
    # Verify hand-written resources_list_resources is preserved
    assert "resources_list_resources" in TOOL_REGISTRY
    hand_written = TOOL_REGISTRY["resources_list_resources"]
    # The hand-written handler comes from vertical_modules.resources.mcp_handlers
    assert "handle_resources_list_resources" in getattr(hand_written.handler, "__name__", "")


def test_resource_tool_collision_detection_raises_runtime_error():
    """Verify that registering a ResourceSpec that collides with an existing tool raises RuntimeError."""
    colliding_spec = ResourceSpec(
        engine="resources",
        entity="resources",
        node_type="RESOURCE",
        id_field="id",
        table_name="allocations",
    )

    generated_tools = build_mcp_tool_specs(colliding_spec)
    # The generated tools include resources_list_resources
    assert "resources_list_resources" in generated_tools

    # Simulate the collision guard logic in tool_registry.py
    fake_registry: dict[str, ToolSpec] = {
        "resources_list_resources": TOOL_REGISTRY["resources_list_resources"]
    }

    with pytest.raises(RuntimeError) as exc_info:
        for tool_name, tool_spec in generated_tools.items():
            if tool_name in fake_registry:
                existing = fake_registry[tool_name]
                raise RuntimeError(
                    f"Collision in TOOL_REGISTRY: resource tool '{tool_name}' generated by "
                    f"ResourceSpec(engine='{colliding_spec.engine}', node_type='{colliding_spec.node_type}') "
                    f"collides with an existing hand-written tool (engine='{existing.engine or colliding_spec.engine}'). "
                    "A generated ResourceSpec tool cannot overwrite a hand-written tool."
                )
            fake_registry[tool_name] = tool_spec

    err_msg = str(exc_info.value)
    assert "Collision in TOOL_REGISTRY" in err_msg
    assert "resources_list_resources" in err_msg
    assert "engine='resources'" in err_msg
    assert "node_type='RESOURCE'" in err_msg
    assert "cannot overwrite a hand-written tool" in err_msg


def test_positive_control_guard_permits_non_colliding_and_rejects_colliding():
    """U18 standing positive control: non-colliding tools register cleanly, colliding ones fail."""
    clean_spec = ResourceSpec(
        engine="test_engine",
        entity="unique_items",
        node_type="TEST_NODE",
        id_field="id",
        table_name=None,
    )
    generated = build_mcp_tool_specs(clean_spec)

    fake_registry: dict[str, ToolSpec] = {}
    # First pass: clean registration succeeds
    for tool_name, tool_spec in generated.items():
        assert tool_name not in fake_registry
        fake_registry[tool_name] = tool_spec

    assert len(fake_registry) == 4

    # Second pass: duplicate registration immediately fails
    with pytest.raises(RuntimeError) as exc_info:
        for tool_name, tool_spec in generated.items():
            if tool_name in fake_registry:
                existing = fake_registry[tool_name]
                raise RuntimeError(
                    f"Collision in TOOL_REGISTRY: resource tool '{tool_name}' generated by "
                    f"ResourceSpec(engine='{clean_spec.engine}', node_type='{clean_spec.node_type}') "
                    f"collides with an existing hand-written tool (engine='{existing.engine or clean_spec.engine}'). "
                    "A generated ResourceSpec tool cannot overwrite a hand-written tool."
                )
            fake_registry[tool_name] = tool_spec

    assert "Collision in TOOL_REGISTRY" in str(exc_info.value)
