"""nce.vertical_modules.legal_entities.service — Domain operations for C15 Legal-Entity Register.

Phase A Wave A-5:
The register's own CRUD (register/list/archive/role-management) is generated by the
C12 resource surface from ``resources.py``'s ``LEGAL_ENTITY_SPEC`` and never called
through here. What remains is the read/write pair ``brreg_feed.py``'s BRREG
enrichment (the one hand-written tool the resource surface does not generate) needs
against the register's own row -- see ``mcp_handlers.py``'s module docstring.
Multi-tenant isolated and RLS protected.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from nce.entity_resolution.normalizers import normalize_org_nr
from nce.vertical_modules.legal_entities.models import LegalEntityRecord

# In-memory store for hermetic unit testing and offline harness execution
_MEM_LEGAL_ENTITIES: dict[str, dict[str, LegalEntityRecord]] = {}


def _clear_mem_store() -> None:
    """Clear in-memory storage for hermetic test execution."""
    _MEM_LEGAL_ENTITIES.clear()


# ===========================================================================
# 1. Legal Entity Operations
# ===========================================================================


async def get_legal_entity(
    conn: Any,
    namespace_id: UUID,
    entity_id: UUID,
) -> LegalEntityRecord | None:
    """Retrieve a legal entity by its primary UUID."""
    if conn is not None:
        query = """
            SELECT id, namespace_id, org_nr, name, group_parent_org_nr,
                   roles, country, metadata, archived, created_at, updated_at
            FROM legal_entities
            WHERE namespace_id = $1 AND id = $2
        """
        row = await conn.fetchrow(query, namespace_id, entity_id)
        if not row:
            return None
        roles_val = row["roles"]
        if isinstance(roles_val, str):
            roles_val = json.loads(roles_val)
        meta_val = row["metadata"]
        if isinstance(meta_val, str):
            meta_val = json.loads(meta_val)
        return LegalEntityRecord(
            id=row["id"],
            namespace_id=row["namespace_id"],
            org_nr=row["org_nr"],
            name=row["name"],
            group_parent_org_nr=row["group_parent_org_nr"],
            roles=tuple(roles_val or ()),
            country=row["country"],
            metadata=dict(meta_val or {}),
            archived=row["archived"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )

    return _MEM_LEGAL_ENTITIES.get(str(namespace_id), {}).get(str(entity_id))


async def update_legal_entity(
    conn: Any,
    namespace_id: UUID,
    entity_id: UUID,
    *,
    name: str | None = None,
    group_parent_org_nr: str | None = None,
    roles: tuple[str, ...] | list[str] | None = None,
    country: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> LegalEntityRecord | None:
    """Update fields on an existing legal entity."""
    existing = await get_legal_entity(conn, namespace_id, entity_id)
    if not existing:
        return None

    now = datetime.now(timezone.utc)
    new_name = name if name is not None else existing.name
    new_parent = (
        normalize_org_nr(group_parent_org_nr)
        if group_parent_org_nr is not None
        else existing.group_parent_org_nr
    )
    new_roles = tuple(sorted(set(roles))) if roles is not None else existing.roles
    new_country = country if country is not None else existing.country
    new_meta = (
        {**existing.metadata, **(metadata or {})} if metadata is not None else existing.metadata
    )

    if conn is not None:
        query = """
            UPDATE legal_entities
            SET name = $1,
                group_parent_org_nr = $2,
                roles = $3::jsonb,
                country = $4,
                metadata = $5::jsonb,
                updated_at = $6
            WHERE namespace_id = $7 AND id = $8
            RETURNING id, namespace_id, org_nr, name, group_parent_org_nr,
                      roles, country, metadata, archived, created_at, updated_at
        """
        row = await conn.fetchrow(
            query,
            new_name,
            new_parent,
            json.dumps(list(new_roles)),
            new_country,
            json.dumps(new_meta),
            now,
            namespace_id,
            entity_id,
        )
        if not row:
            return None
        roles_val = row["roles"]
        if isinstance(roles_val, str):
            roles_val = json.loads(roles_val)
        meta_val = row["metadata"]
        if isinstance(meta_val, str):
            meta_val = json.loads(meta_val)
        return LegalEntityRecord(
            id=row["id"],
            namespace_id=row["namespace_id"],
            org_nr=row["org_nr"],
            name=row["name"],
            group_parent_org_nr=row["group_parent_org_nr"],
            roles=tuple(roles_val or ()),
            country=row["country"],
            metadata=dict(meta_val or {}),
            archived=row["archived"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )

    updated = LegalEntityRecord(
        id=existing.id,
        namespace_id=existing.namespace_id,
        org_nr=existing.org_nr,
        name=new_name,
        group_parent_org_nr=new_parent,
        roles=new_roles,
        country=new_country,
        metadata=new_meta,
        archived=existing.archived,
        created_at=existing.created_at,
        updated_at=now,
    )
    _MEM_LEGAL_ENTITIES[str(namespace_id)][str(entity_id)] = updated
    return updated
